config/routes.rb
Swprototype::Application.routes.draw do
  get "home/index"

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  constraints(Subdomain) do
    root to:  "bar_home#index"
    match "/" => "bar_home#index", as: "bar_home"
    devise_scope :bar do
      match "/sign_in" => "bars/sessions#new", :as => :sign_in_bars
      match "/sign_up" =>  "bars/registrations#new", :as => :sign_up_bars
    end
  end

  root to:  "home#main"
  
  match "bars/city/:id" =>  "home#city", as: "city"
  get "live_swig_feed" =>  "request#live_swig_feed", as: "live_swig_feed"
  get "set_time_zone" =>  "application#set_time_zone", as: "set_time_zone"

  resource :home do
    collection do
      get "main" =>  "home#main", as: "main"
      get "contact_us" =>  "home#contact_us", as: "contact_us"
      get "contact_us_for_homepage" =>  "home#contact_us_for_homepage", as: "contact_us_for_homepage"
      post "create_contact_us" =>  "home#create_contact_us", as: "create_contact_us"
      get "bars_list_to_swig" =>  "home#bars_list_to_swig", as: "bars_list_to_swig"
      get "mobile_dashboard" =>  "home#mobile_dashboard", as: "mobile_dashboard"
      match "sign_out_turning_point" =>  "home#sign_out_turning_point", as: "sign_out_turning_point"
    end
  end

  resource :request do 
    collection do
      match "invitations" =>  "request#invitations", as: "invitations"
      post "create_request" =>  "request#create_request", as: "create_request"
      match "welcome" =>  "request#welcome", as: "welcome"
      post "login_to_swigbig" =>  "request#login_to_swigbig", as: "login_to_swigbig"
      match "login" =>  "request#login", as: "login"
      match "select_type" =>  "request#select_type", as: "select_type"
    end
  end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", confirmations: "users/confirmations",passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}
  devise_scope :user do
    post "/update_picture_from_facebook" => "users/omniauth_callbacks#update_picture_from_facebook", :as => :update_picture_from_facebook
  end

  get "bar/:bar_id" => "users/bars#show", as: "bar_profile"
  
  resource :users do
    collection do
    end
  end
  
  devise_for :bars, controllers: {registrations: "bars/registrations", sessions: "bars/sessions", confirmations: "bars/confirmations", passwords: "bars/passwords"}

  devise_for :members, controllers: {registrations: "members/registrations"}
  
  namespace :bars do
    get "delete_swig/:id" => "dashboard#delete_swig", as: "delete_swig"
    match  "invite_friend" => "dashboard#after_join_invite_friends", as: "after_join_invite_friends"
    post  "invite_friend_by_email" => "dashboard#invite_friend_by_email", as: "invite_friend_by_email"
    match  "sport_lists" => "dashboard#sport_lists", as: "sport_lists"
    match  "users_lists" => "dashboard#users_lists", as: "users_lists"
    match  "completion" => "dashboard#completion", as: "completion"
    post  "update_completion" => "dashboard#update_completion", as: "update_completion"
    match  "second_completion" => "dashboard#second_completion", as: "second_completion"
    post  "update_second_completion" => "dashboard#update_second_completion", as: "update_second_completion"
    match  "dashboard" => "dashboard#index", as: "dashboard"
    match  "product" => "products#index", as: "product"
    post  "create_reward_message/:user_id/:winner_id" => "dashboard#create_reward_message", as: "create_reward_message"
    post  "create_swig" => "dashboard#create_swig", as: "create_swig"
    post  "create_big_swig" => "dashboard#create_big_swig", as: "create_big_swig"
    post  "update_big_swig" => "dashboard#update_big_swig", as: "update_big_swig"
    get  "delete_big_swig/:ids" => "dashboard#delete_big_swig", as: "delete_big_swig"
    post  "update_swig/:id" => "dashboard#update_swig", as: "update_swig"
    post  "create_loyalty" => "dashboard#create_loyalty", as: "create_loyalty"
    post  "create_popularity" => "dashboard#create_popularity", as: "create_popularity"
    get "edit_loyalty/:id" => "dashboard#edit_loyalty", as: :edit_loyalty
    get "new_loyalty" => "dashboard#new_loyalty", as: :new_loyalty
    get "edit_popularity/:id" => "dashboard#edit_popularity", as: :edit_popularity
    get "new_popularity" => "dashboard#new_popularity", as: :new_popularity
    post  "update_loyalty/:id" => "dashboard#update_loyalty", as: "update_loyalty"
    post  "update_popularity/:id" => "dashboard#update_popularity", as: "update_popularity"
    delete  "delete_loyalty/:id" => "dashboard#delete_loyalty", as: "delete_loyalty"
    delete  "delete_popularity/:id" => "dashboard#delete_popularity", as: "delete_popularity"
    get "rewards/index"
    match "rewards" => "rewards#index", as: "rewards"
    post "create_bar_message" => "dashboard#create_bar_message", as: "create_bar_message"
    post  "create_gift" => "dashboard#create_gift", as: "create_gift"
    post  "activate_loyalty/:loyalty_id" => "dashboard#activate_loyalty", as: "activate_loyalty"
    post  "deactivate_loyalty/:loyalty_id" => "dashboard#deactivate_loyalty", as: "deactivate_loyalty"
    post  "activate_popularity/:popularity_id" => "dashboard#activate_popularity", as: "activate_popularity"
    post  "deactivate_popularity/:popularity_id" => "dashboard#deactivate_popularity", as: "deactivate_popularity"
    post  "update_gift/:gift_id" => "dashboard#update_gift", as: "update_gift"
    get  "destroy_gift_in_list/:gift_id" => "dashboard#destroy_gift_in_list", as: "destroy_gift_in_list"
    post  "add_bigswig_list" => "dashboard#add_bigswig_list", as: "add_bigswig_list"
    post  "add_bigswig_list_on_update" => "dashboard#add_bigswig_list_on_update", as: "add_bigswig_list_on_update"
    post  "add_bar_hours" => "dashboard#add_bar_hours", as: "add_bar_hours"
    post  "add_bar_hours_on_edit" => "dashboard#add_bar_hours_on_edit", as: "add_bar_hours_on_edit"
    post  "add_reward_to_list" => "dashboard#add_reward_to_list", as: "add_reward_to_list"
    get  "destroy_bar_big_swig_list/:bigswiglist_id" => "dashboard#destroy_bar_big_swig_list", as: "destroy_bar_big_swig_list"
    post  "update_bar_big_swig_list/:bigswiglist_id" => "dashboard#update_bar_big_swig_list", as: "update_bar_big_swig_list"
    post  "search_redeem_code/:code" => "dashboard#search_redeem_code", as: "search_redeem_code"
    get  "swiger_list" => "dashboard#swiger_list", as: "swiger_list"
    post  "update_bar_hours" => "dashboard#update_bar_hours", as: "update_bar_hours"
    get  "swigger_total_count" => "dashboard#swigger_total_count", as: "swigger_total_count"
    get "reward_stats" => "dashboard#reward_stats", as: :reward_stats

    resources :messages do
      collection do
        get  "notify_mark_all_read" => "messages#notify_mark_all_read", as: "notify_mark_all_read"
        get  "messages_mark_all_read" => "messages#messages_mark_all_read", as: "messages_mark_all_read"
        get 'notifications'
        get 'sent'
        post 'custom_action(/:form_type)' => "messages#custom_action", as: :custom_action
        get 'trash'
        get 'message_popup'
        get 'new/:user_ids' => "messages#new", as: :new
        post 'reply_message'

      end
    end

  end
  
  resources :bars do
    match "upgrade" => "bars/payment_gateway#index", as: "upgrade"
  end

  namespace :users do
    match  "invite_friend" => "dashboard#after_join_invite_friends_by_email", as: "after_join_invite_friends_by_email"
    match  "invite_friends" => "dashboard#after_join_invite_friends_by_fb", as: "after_join_invite_friends_by_fb"
    post  "invite_friend_by_email" => "dashboard#after_sign_up_invite_friend_by_email", as: "after_sign_up_invite_friend_by_email"
    post  "invite_friend_by_fb" => "dashboard#after_sign_up_invite_friend_by_fb", as: "after_sign_up_invite_friend_by_fb"
    post  "update_user_for_mobile" => "dashboard#update_user_for_mobile", as: "update_user_for_mobile"
    match  "completion" => "dashboard#completion", as: "completion"
    post  "update_completion" => "dashboard#update_completion", as: "update_completion"
    match  "notifications" => "notifications#index", as: "notifications"
    match  "user_dashboard" => "dashboard#index", as: "dashboard"
    match  "facebook_dashboard" => "dashboard#facebook_page", as: "facebook_page"
    match  "facebook_mobile_profile" => "dashboard#facebook_mobile_profile", as: "facebook_mobile_profile"
    match  "facebook_update_status" => "dashboard#facebook_update_status", as: "facebook_update_status"
    match  "invite_swigbig" => "dashboard#invite_swigbig", as: "invite_swigbig"
    post "invite_by_email" => "dashboard#invite_by_email", as: :invite_by_email
    match  "profile/:id" => "dashboard#show", as: "profile"
    match  "rewards" => "dashboard#rewards", as: "rewards"
    match  "update_account" => "dashboard#update_account", as: "update_account"
    match  "update_password" => "dashboard#update_password", as: "update_password"
    get  "show_swig/:bar_id/:swig_id" => "bar_swigs#show_swig", as: "show_swig"
    post  "enter_bar/:bar_id" => "bar_swigs#enter_bar", as: "enter_bar"
    post  "redeem/:bar_id" => "bars#redeem_reward", as: "redeem_reward"
    post "create_popularity/:bar_id" => "bars#create_popularity", as: "create_popularity"
    match "friendship" => "friends#index", as: "friend_index"
    post "friend_request/:id" => "friends#friend_request", as: "friend_request"
    post "remove_friend/:id" => "friends#remove_friend", as: :remove_friend
    post "approve_friend/:id" => "friends#approve_friend", as: :approve_friend
    get  "swiger_list/:bar_id" => "bars#swiger_list", as: "swiger_list"
    get  "mobile_reward" => "dashboard#mobile_reward", as: "mobile_reward"
    get  "lock_post_event" => "dashboard#lock_post_event", as: "lock_post_event"
    get  "unlock_post_event" => "dashboard#unlock_post_event", as: "unlock_post_event"

app/views/shared/_bar_hours_add_partial.html.erb
<div id="bar_hour_list<%= count %>">
  <div style="margin-left: 31px;">
    <% unless count.eql?(0) %>
      <a onclick='$("#bar_hour_list<%= count %>").remove()'><i class="icon-remove"></i></a>
    <% end %>
    <%= select_tag "first_day_#{count}", options_for_select(days), {style: "width: 100px;margin-bottom: 3px;"} %>
    to
    <%= select_tag "last_day#{count}", options_for_select(days), {style: "width: 100px;margin-bottom: 3px;"} %>
    <%= select_tag "open_hour#{count}", options_for_select(hours_collection), {style: "width: 50px;margin-bottom: 3px;"} %>
    <%= select_tag "open_word#{count}", options_for_select([["AM","AM"],["PM","PM"]]), {style: "width: 50px;margin-bottom: 3px;"} %>
    <%= select_tag "close_hour#{count}", options_for_select(hours_collection), {style: "width: 50px;margin-bottom: 3px;"} %>
    <%= select_tag "close_word#{count}", options_for_select([["AM","AM"],["PM","PM"]]), {style: "width: 50px;margin-bottom: 3px;"} %>
    <b> close </b>
    <%= check_box_tag "close_day#{count}" %>
  </div>
</div>
<div class="clearfix"></div>

app/views/shared/_bar_modal_partial.html.erb
<% if bar_signed_in? %>
  <div id="bar_message" class="modal hide fade"></div>
<% end %>
  

app/views/shared/_footer_menu_partial.mobile.erb
<div data-role="controlgroup" data-type="horizontal" style="margin: 5px;width: 100%;" >

  <% unless user_signed_in? %>

    <a class="" data-role="button" onclick="window.location.href='<%= main_home_url(:mobile) %>'"  style="width: 49%;">DEALS</a>
    <a class="" data-role="button" onclick="window.location.href='<%= mobile_dashboard_home_url(:mobile) %>'"  style="width: 49%;">LOG IN</a>

  <% else %>

    <a class="" data-role="button" onclick="window.location.href='<%= main_home_url(:mobile) %>'"  style="width: 33%;">Deals</a>
    <a class="" data-role="button" onclick="window.location.href='<%= users_mobile_reward_url(:mobile) %>'"  style="width: 33%;">Rewards</a>

    <% unless current_user.fb_id.blank? %>
      <a class="" data-role="button" onclick="window.location.href='<%= users_facebook_mobile_profile_url(:mobile) %>'"  style="width: 33%;">Account</a>
    <% else %>
      <a class="" data-role="button" onclick="window.location.href='<%= users_dashboard_url(:mobile) %>'"  style="width: 33%;">Account</a>
    <% end %>

  <% end %>

</div>

app/views/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/shared/_new_message_form_popup.html.erb
<style type="text/css">
  ul.token-input-list-facebook{
    margin-left: -105px;
    width: 430px;
  }
</style>
<script type="text/javascript">
  $(document).ready(function() {
    var users = [];
<% User.all.each do |b| %>
      var x = [];
      x.push('name: <%= b.to_json %>');//0
      x.push('id: <%= b.to_json %>');//0
      users.push(x);
<% end %>

    $("#tk_users").tokenInput("/bars/users_lists", {
      theme: "facebook",
      preventDuplicates: true
    });
  });
</script>

<div class="modal-header">
  <a class="close" data-dismiss="modal"><b>x</b></a>
  <h3>New Message</h3>
</div>
<div class="modal-body well">
  <ul class="tabs" data-tabs="tabs">
    <li><a href="#personal" class="btn" data-toggle="tab"><b style="font-size: 11px;">Select User</b></a></li>
    <li><a href="#last_visit" class="btn" data-toggle="tab"><b style="font-size: 11px;">Last Visit</b></a></li>
    <li><a href="#almost_rewarded" class="btn" data-toggle="tab"><b style="font-size: 11px;">Almost Rewarded</b></a></li>
    <li><a href="#unused_rewards" class="btn" data-toggle="tab"><b style="font-size: 11px;">Unused Rewarded</b></a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="personal">
      <%= simple_form_for(@bar_message ,url: bars_create_bar_message_path) do |m| %>
        <div style="margin-bottom: -30px;margin-left: 14px;"><b>To: </b></div>
        <div style="margin-top: 10px;">
          <%= m.input :to, label: false, input_html: {id: "tk_users"} %>
        </div>
        <div style="margin-left: -105px;">
          <%= m.input :gift_id,label: "<b>Gift:</b>".html_safe, as: :select, collection: gift_collections,  input_html: {style: "width: 430px;"} %>
        </div>
        <div style="margin-bottom: -20px;margin-left: -15px;">
          <b>Subject: </b>
        </div>
        <%= m.input :topic, label: false, input_html: {style: "margin-left: -105px;width: 420px;margin-bottom: 40px"} %>
        <div style="margin-top: -45px;">
  <%#= m.input :expirate_reward, label: false, as: :string,  placeholder: "Reward Expirate Date", input_html: {class: "datepicker", style: "width: 135px;margin-left: 170px;"} %>
        </div>
        <%= m.input :category, as: :hidden, input_html: {value: 5} %>
        <div style="text-align: center;">
          <%= m.input :body, input_html: {style: "margin-left: -180px;width: 445px;height: 104px;"} %>
        </div>
        <div class="form-actions">
          <a href="#" class="btn pull-left" data-dismiss="modal" >Cancel</a>
          <%= m.submit "Send", class: "btn-success pull-right" %>
          </div>
        <% end %>
      </div>

      <div class="tab-pane" id="last_visit">
        <%= simple_form_for(@bar_message ,url: bars_create_bar_message_path) do |m| %>
          <div style="margin-left: 20px;"><b>To: </b> All User that nave not swiggerd here in </div>
          <%= text_field_tag :days, "",style: "width: 40px;margin-right: 150px;margin-top: -20px;", class: "pull-right", placeholder: "days" %>
            <div style="margin-top: 20px;margin-bottom: -20px;margin-left: 20px;">
              <b>Gift: </b>
            </div>
            <div style="margin-left: -90px;">
              <%= m.input :gift_id, label: false, as: :select, collection: gift_collections,  style: "margin-left: -75px;" %>
            </div>
            <div style="margin-top: 20px;margin-bottom: -20px;margin-left: 20px;">
              <b>Subject: </b>
            </div>
            <%= m.input :topic, label: false, placeholder: "Subject", input_html: {style: "margin-left: -80px;width: 300px;"} %>
            <%= m.input :category, as: :hidden, input_html: {value: 1} %>
            <div style="text-align: center;">
              <%= m.input :body, input_html: {style: "margin-left: -180px;width: 445px;height: 104px;"} %>
            </div>
            <div class="form-actions">
              <a href="#" class="btn pull-left" data-dismiss="modal" >Cancel</a>
              <%= m.submit "Send", class: "btn-success pull-right" %>
              </div>
            <% end %>
          </div>

          <div class="tab-pane" id="almost_rewarded">
            <%= simple_form_for(@bar_message ,url: bars_create_bar_message_path) do |m| %>
              <!--<div style="margin-left: -105px;">
        <%#= m.input :gift_id, as: :select, collection: gift_collections,  style: "margin-left: -75px;" %>
              </div>
              <div style="margin-top: -45px;">
        <%#= m.input :expirate_reward, label: false, as: :string,  placeholder: "Reward Expirate Date", input_html: {class: "datepicker", style: "width: 135px;margin-left: 170px;"} %>
                </div>-->
              <div style=""><p><b>To: </b> All users that will earn a reward within</p></div>
              <div style="margin-bottom: 20px;margin-top: -30px;">
                <%= text_field_tag :required_swigs, "",style: "width: 40px;margin-right: 155px;", class: "pull-right", placeholder: "Swigs required" %>
                </div>
                <div style="margin-top: 50px;"><b>Subject:</b></div>
                <div style="margin-top: -15px;">
                  <%= m.input :topic, label: "Subject", placeholder: "Subject", input_html: {style: "margin-left: -80px;width: 300px;"} %>
                </div>
                <%= m.input :category, as: :hidden, input_html: {value: 2} %>
                <div style="text-align: center;">
                  <%= m.input :body, input_html: {style: "margin-left: -180px;width: 445px;height: 104px;"} %>
                </div>
                <div class="form-actions">
                  <a href="#" class="btn pull-left" data-dismiss="modal" >Cancel</a>
                  <%= m.submit "Send", class: "btn-success pull-right" %>
                  </div>
                <% end %>
              </div>
              <div class="tab-pane" id="unused_rewards">
                <%= simple_form_for(@bar_message ,url: bars_create_bar_message_path) do |m| %>
                  <div style=""><p><b>To: </b> All users that have not used their rewards</p></div>
                  <div style="margin-bottom: 20px;margin-top: -30px;">
            <%#= text_field_tag :required_swigs, "",style: "width: 40px;margin-right: 155px;", class: "pull-right", placeholder: "Swigs required" %>
                  </div>
                  <div style="margin-top: 50px;"><b>Subject:</b></div>
                  <div style="margin-top: -15px;">
                    <%= m.input :topic, label: "Subject", placeholder: "Subject", input_html: {style: "margin-left: -80px;width: 300px;"} %>
                  </div>
                  <%= m.input :category, as: :hidden, input_html: {value: 17} %>
                  <div style="text-align: center;">
                    <%= m.input :body, input_html: {style: "margin-left: -180px;width: 445px;height: 104px;"} %>
                  </div>
                  <div class="form-actions">
                    <a href="#" class="btn pull-left" data-dismiss="modal" >Cancel</a>
                    <%= m.submit "Send", class: "btn-success pull-right" %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>

app/views/shared/_swigbig_logo.html.erb
<div style="width: 100%; height: 100px; position: relative; background-color: #fbfbfb; border: 1px solid #b8b8b8;">
  <% if !@site_content.blank? %>
    <% if !@site_content.logos.blank? %>
      <%= image_tag(@site_content.logos.status_active.first.image_url, style: "height: 100px;") rescue nil %>
    <% else %>
      <h3 class="brand" style="color: white;">SwigBIG</h3>
    <% end %>
  <% else %>
    <h3 class="brand" style="color: white;">SwigBIG</h3>
  <% end %>
</div>

app/views/shared/_users_header.html.erb
<div class="navbar-fixed-top" style="">
  <div class="navbar-inner" >
    <div class="container" >
      <div class="nav pull-right">
        <li>
          <% if !@site_content.blank? %>
            <% if !@site_content.logos.blank? %>
              <%= link_to image_tag(@site_content.logos.status_active.first.image_url, style: "height: 45px;"), root_path, style: "padding: 0px;" %>
    <%#= image_tag(@site_content.logos.status_active.first.image_url, style: "height: 45px;") rescue nil %>
            <% else %>
              <h3 class="brand" style="color: white;"><%= link_to "SwigBIG", root_path, style: "color: white;" %></h3>
            <% end %>
          <% else %>
            <h3 class="brand" style="color: white;"><%= link_to "SwigBIG", root_path, style: "color: white;" %></h3>
          <% end %>
        </li>
        <li>
          <h2 class="brand" style="color: gray;"><h3>&nbsp; on <span id="day_swig"><%= Time.zone.now.strftime('%A') %></span></h3></h2>
        </li>
        <div class="nav pull-right" >

          <div style="display: none;"><%= link_to "Home", main_home_path, style: "color: white;" %></div>
          <li><b><a href="#learn_more" data-toggle="modal" id="fat-menu" style="color: white;">Learn More</a></b></li>
          <% unless user_signed_in? %>
            <li>
              <b><%= link_to "Sign Up for Free", new_user_registration_path,style: "color:#fff" %></b>
            </li>
          <% end %>
          <% if user_signed_in? %>

            <li id="user_notification" class="dropdown">
              <a class="dropdown-toggle" href="" data-toggle="dropdown" onclick="$('#notify_goto_unread').click();" ><b style="color: white;">Notifications&nbsp;</b><span class="badge badge-error" id="notify_red"><%=  current_user.received_messages.where("notify_opended is false").count %></span></a>
              <ul class="dropdown-menu">
                <div style="display: none;">
                  <% unless  current_user.received_messages.where("notify_opended is false").blank? %>
                    <%= link_to "to_unread", notify_mark_all_read_users_messages_path, id: 'notify_goto_unread', remote: true %>
                  <% end %>
                </div>
                <% current_user.received_messages.where("notify_opended is false").each do |notification| %>
                  <li style="width: 220px;" ><%= notification.topic.html_safe %>
                    <br/>
                    <%= notification.created_at.strftime("%v") %>
                  </li>
                  <li class="divider"></li>
                <% end %>
                <li>
                  <b><%=  link_to "See All", notifications_users_messages_path, style: "color: white;" %></b>
                </li>
              </ul>
            </li>

            <li id="user_messages" class="dropdown">
              <a class="dropdown-toggle" href="" data-toggle="dropdown" onclick="$('#message_goto_unread').click();" ><b style="color: white;">Messages&nbsp;</b><span class="badge badge-error" id="messages_red"><%=  current_user.received_messages.where(["opened IS false AND category != (?)", ("10, 18")]).count %></span></a>
              <ul class="dropdown-menu">
                <div style="display: none;">
                  <% unless  current_user.received_messages.where(["opened IS false AND category != (?)", ("10, 18")]).blank? %>
                    <%= link_to "to_unread", messages_mark_all_read_users_messages_path, id: 'message_goto_unread', remote: true %>
                  <% end %>
                </div>
                <% current_user.received_messages.where(["opened IS false AND category != (?)", ("10, 18")]).each do |notification| %>
                  <li style="width: 220px;" ><%= notification.topic.html_safe %>
                    <br/>
                    <%= notification.created_at.strftime("%v") %>
                  </li>
                  <li class="divider"></li>
                <% end %>
                <li>
                  <b><%=  link_to "See All", users_messages_path, style: "color: white;" %></b>
                </li>
              </ul>
            </li>

            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: white;"><b><%= "Welcome back #{(current_user.name || current_user.email ).split(" ").first }!" %></b></a>
              <ul class="dropdown-menu">
                <% unless current_user.access_token.blank? %>
                  <b><%= link_to "Profile", users_facebook_page_path, style: "color: white;" %></b>
                <% else %>
                  <li>
                    <b><%= link_to "Profile", users_profile_path(current_user), style: "color: white;" %></b>
                  </li>
                <% end %>
                <li>
                  <%= link_to "Rewards", users_rewards_path %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li>
              <b><%= link_to "Log In", new_user_session_path, style: "color: white" %></b>
            </li>
          <% end %>
        </div>
      </div>
    </div>
    <% if user_signed_in? %>
      <% if current_user.bird_date.blank? and current_user.access_token.blank?%>
        <div style="text-align: center;color: red;" id="red_notice"><i class="icon-warning-sign"></i><b> <%= (current_user.name || "" ).split(" ").first %></b> Profile not complete yet!Click <a href="#user_details" data-toggle="modal" id="completion_link">here</a> to complete your profile!<a class="close" onclick="$('#red_notice').toggle()"><b>x</b></a></div>
      <% end %>
    <% end %>
  </div>
</div>