config/routes.rb
Swprototype::Application.routes.draw do
  get "home/index"

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  constraints(Subdomain) do
    root to:  "bar_home#index"
    match "/" => "bar_home#index", as: "bar_home"
    devise_scope :bar do
      match "/sign_in" => "bars/sessions#new", :as => :sign_in_bars
      match "/sign_up" =>  "bars/registrations#new", :as => :sign_up_bars
    end
  end

  root to:  "home#main"
  
  match "bars/city/:id" =>  "home#city", as: "city"
  get "live_swig_feed" =>  "request#live_swig_feed", as: "live_swig_feed"
  get "set_time_zone" =>  "application#set_time_zone", as: "set_time_zone"

  resource :home do
    collection do
      get "main" =>  "home#main", as: "main"
      get "contact_us" =>  "home#contact_us", as: "contact_us"
      get "contact_us_for_homepage" =>  "home#contact_us_for_homepage", as: "contact_us_for_homepage"
      post "create_contact_us" =>  "home#create_contact_us", as: "create_contact_us"
      get "bars_list_to_swig" =>  "home#bars_list_to_swig", as: "bars_list_to_swig"
      get "mobile_dashboard" =>  "home#mobile_dashboard", as: "mobile_dashboard"
      match "sign_out_turning_point" =>  "home#sign_out_turning_point", as: "sign_out_turning_point"
    end
  end

  resource :request do 
    collection do
      match "invitations" =>  "request#invitations", as: "invitations"
      post "create_request" =>  "request#create_request", as: "create_request"
      match "welcome" =>  "request#welcome", as: "welcome"
      post "login_to_swigbig" =>  "request#login_to_swigbig", as: "login_to_swigbig"
      match "login" =>  "request#login", as: "login"
      match "select_type" =>  "request#select_type", as: "select_type"
    end
  end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", confirmations: "users/confirmations",passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}
  devise_scope :user do
    post "/update_picture_from_facebook" => "users/omniauth_callbacks#update_picture_from_facebook", :as => :update_picture_from_facebook
  end

  get "bar/:bar_id" => "users/bars#show", as: "bar_profile"
  
  resource :users do
    collection do
    end
  end
  
  devise_for :bars, controllers: {registrations: "bars/registrations", sessions: "bars/sessions", confirmations: "bars/confirmations", passwords: "bars/passwords"}

  devise_for :members, controllers: {registrations: "members/registrations"}
  
  namespace :bars do
    get "delete_swig/:id" => "dashboard#delete_swig", as: "delete_swig"
    match  "invite_friend" => "dashboard#after_join_invite_friends", as: "after_join_invite_friends"
    post  "invite_friend_by_email" => "dashboard#invite_friend_by_email", as: "invite_friend_by_email"
    match  "sport_lists" => "dashboard#sport_lists", as: "sport_lists"
    match  "users_lists" => "dashboard#users_lists", as: "users_lists"
    match  "completion" => "dashboard#completion", as: "completion"
    post  "update_completion" => "dashboard#update_completion", as: "update_completion"
    match  "second_completion" => "dashboard#second_completion", as: "second_completion"
    post  "update_second_completion" => "dashboard#update_second_completion", as: "update_second_completion"
    match  "dashboard" => "dashboard#index", as: "dashboard"
    match  "product" => "products#index", as: "product"
    post  "create_reward_message/:user_id/:winner_id" => "dashboard#create_reward_message", as: "create_reward_message"
    post  "create_swig" => "dashboard#create_swig", as: "create_swig"
    post  "create_big_swig" => "dashboard#create_big_swig", as: "create_big_swig"
    post  "update_big_swig" => "dashboard#update_big_swig", as: "update_big_swig"
    get  "delete_big_swig/:ids" => "dashboard#delete_big_swig", as: "delete_big_swig"
    post  "update_swig/:id" => "dashboard#update_swig", as: "update_swig"
    post  "create_loyalty" => "dashboard#create_loyalty", as: "create_loyalty"
    post  "create_popularity" => "dashboard#create_popularity", as: "create_popularity"
    get "edit_loyalty/:id" => "dashboard#edit_loyalty", as: :edit_loyalty
    get "new_loyalty" => "dashboard#new_loyalty", as: :new_loyalty
    get "edit_popularity/:id" => "dashboard#edit_popularity", as: :edit_popularity
    get "new_popularity" => "dashboard#new_popularity", as: :new_popularity
    post  "update_loyalty/:id" => "dashboard#update_loyalty", as: "update_loyalty"
    post  "update_popularity/:id" => "dashboard#update_popularity", as: "update_popularity"
    delete  "delete_loyalty/:id" => "dashboard#delete_loyalty", as: "delete_loyalty"
    delete  "delete_popularity/:id" => "dashboard#delete_popularity", as: "delete_popularity"
    get "rewards/index"
    match "rewards" => "rewards#index", as: "rewards"
    post "create_bar_message" => "dashboard#create_bar_message", as: "create_bar_message"
    post  "create_gift" => "dashboard#create_gift", as: "create_gift"
    post  "activate_loyalty/:loyalty_id" => "dashboard#activate_loyalty", as: "activate_loyalty"
    post  "deactivate_loyalty/:loyalty_id" => "dashboard#deactivate_loyalty", as: "deactivate_loyalty"
    post  "activate_popularity/:popularity_id" => "dashboard#activate_popularity", as: "activate_popularity"
    post  "deactivate_popularity/:popularity_id" => "dashboard#deactivate_popularity", as: "deactivate_popularity"
    post  "update_gift/:gift_id" => "dashboard#update_gift", as: "update_gift"
    get  "destroy_gift_in_list/:gift_id" => "dashboard#destroy_gift_in_list", as: "destroy_gift_in_list"
    post  "add_bigswig_list" => "dashboard#add_bigswig_list", as: "add_bigswig_list"
    post  "add_bigswig_list_on_update" => "dashboard#add_bigswig_list_on_update", as: "add_bigswig_list_on_update"
    post  "add_bar_hours" => "dashboard#add_bar_hours", as: "add_bar_hours"
    post  "add_bar_hours_on_edit" => "dashboard#add_bar_hours_on_edit", as: "add_bar_hours_on_edit"
    post  "add_reward_to_list" => "dashboard#add_reward_to_list", as: "add_reward_to_list"
    get  "destroy_bar_big_swig_list/:bigswiglist_id" => "dashboard#destroy_bar_big_swig_list", as: "destroy_bar_big_swig_list"
    post  "update_bar_big_swig_list/:bigswiglist_id" => "dashboard#update_bar_big_swig_list", as: "update_bar_big_swig_list"
    post  "search_redeem_code/:code" => "dashboard#search_redeem_code", as: "search_redeem_code"
    get  "swiger_list" => "dashboard#swiger_list", as: "swiger_list"
    post  "update_bar_hours" => "dashboard#update_bar_hours", as: "update_bar_hours"
    get  "swigger_total_count" => "dashboard#swigger_total_count", as: "swigger_total_count"
    get "reward_stats" => "dashboard#reward_stats", as: :reward_stats

    resources :messages do
      collection do
        get  "notify_mark_all_read" => "messages#notify_mark_all_read", as: "notify_mark_all_read"
        get  "messages_mark_all_read" => "messages#messages_mark_all_read", as: "messages_mark_all_read"
        get 'notifications'
        get 'sent'
        post 'custom_action(/:form_type)' => "messages#custom_action", as: :custom_action
        get 'trash'
        get 'message_popup'
        get 'new/:user_ids' => "messages#new", as: :new
        post 'reply_message'

      end
    end

  end
  
  resources :bars do
    match "upgrade" => "bars/payment_gateway#index", as: "upgrade"
  end

  namespace :users do
    match  "invite_friend" => "dashboard#after_join_invite_friends_by_email", as: "after_join_invite_friends_by_email"
    match  "invite_friends" => "dashboard#after_join_invite_friends_by_fb", as: "after_join_invite_friends_by_fb"
    post  "invite_friend_by_email" => "dashboard#after_sign_up_invite_friend_by_email", as: "after_sign_up_invite_friend_by_email"
    post  "invite_friend_by_fb" => "dashboard#after_sign_up_invite_friend_by_fb", as: "after_sign_up_invite_friend_by_fb"
    post  "update_user_for_mobile" => "dashboard#update_user_for_mobile", as: "update_user_for_mobile"
    match  "completion" => "dashboard#completion", as: "completion"
    post  "update_completion" => "dashboard#update_completion", as: "update_completion"
    match  "notifications" => "notifications#index", as: "notifications"
    match  "user_dashboard" => "dashboard#index", as: "dashboard"
    match  "facebook_dashboard" => "dashboard#facebook_page", as: "facebook_page"
    match  "facebook_mobile_profile" => "dashboard#facebook_mobile_profile", as: "facebook_mobile_profile"
    match  "facebook_update_status" => "dashboard#facebook_update_status", as: "facebook_update_status"
    match  "invite_swigbig" => "dashboard#invite_swigbig", as: "invite_swigbig"
    post "invite_by_email" => "dashboard#invite_by_email", as: :invite_by_email
    match  "profile/:id" => "dashboard#show", as: "profile"
    match  "rewards" => "dashboard#rewards", as: "rewards"
    match  "update_account" => "dashboard#update_account", as: "update_account"
    match  "update_password" => "dashboard#update_password", as: "update_password"
    get  "show_swig/:bar_id/:swig_id" => "bar_swigs#show_swig", as: "show_swig"
    post  "enter_bar/:bar_id" => "bar_swigs#enter_bar", as: "enter_bar"
    post  "redeem/:bar_id" => "bars#redeem_reward", as: "redeem_reward"
    post "create_popularity/:bar_id" => "bars#create_popularity", as: "create_popularity"
    match "friendship" => "friends#index", as: "friend_index"
    post "friend_request/:id" => "friends#friend_request", as: "friend_request"
    post "remove_friend/:id" => "friends#remove_friend", as: :remove_friend
    post "approve_friend/:id" => "friends#approve_friend", as: :approve_friend
    get  "swiger_list/:bar_id" => "bars#swiger_list", as: "swiger_list"
    get  "mobile_reward" => "dashboard#mobile_reward", as: "mobile_reward"
    get  "lock_post_event" => "dashboard#lock_post_event", as: "lock_post_event"
    get  "unlock_post_event" => "dashboard#unlock_post_event", as: "unlock_post_event"

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "users"

  before_filter :redirect_to_request_invitation_page

  def redirect_to_request_invitation_page
    unless session[:request_user_privilage] or is_mobile_request?
      redirect_to invitations_request_url
    else
      return
    end
  end

  def index; end

  def get_latitude_and_longitude_from_mobile
    data = User.find_by_email(params[:user][:email])
  end

  def main
    @city = City.where(name: @city_lat_lng[0].to_s).first

    if user_signed_in?
      if current_user.access_token
        fb_ids = FbGraph::User.me(current_user.access_token).friends.map(&:identifier)
        fb_friends_ids = User.where(fb_id: fb_ids).pluck(:fb_id)
        @friends_swigger = Swiger.joins(:user).where(["users.fb_id IN (?) AND swigers.created_at >= (?) AND swigers.created_at <= (?)", fb_friends_ids,( Time.zone.now - @swigger_show_within.hours ), Time.zone.now ])
      end
    end

    conditions = []
    conditions << "bars.address IS NOT NULL "
    conditions << "swigs.swig_type = '#{params[:swig_type]}'" unless params[:swig_type].blank?
    conditions << "bars.sports_team LIKE '%#{params[:sports_team]}%'" unless params[:sports_team].blank?
    conditions << "swigs.swig_day = '#{Time.zone.now.strftime("%A").to_s}'"

    @origin = params[:zip_code].blank? ? [@city_lat_lng[1], @city_lat_lng[2]] : params[:zip_code]
    
    unless params[:radius].blank?
      @bars = Bar.within(params[:radius].to_i, origin: @origin).includes(:swigs).where(conditions.join(" AND ")).order("swig_type DESC")
    else
      if is_mobile_request?
        unless session[:after_redirect]
          session[:homepage_request_page] = true
        end

        @bars = Bar.within(@radius_to_show_in_mobile_list ,origin: @origin).includes(:swigs).where(conditions.join(" AND ")).sort_by_distance_from(@origin)#.take(5)
      else
        @bars = Bar.within(@radius_to_show_in_mobile_list ,origin: @origin).includes(:swigs).where(conditions.join(" AND ")).sort_by_distance_from(@origin)
      end
    end
    
    unless params[:zip_code].blank?
      geo = Geocoder.search("#{params[:zip_code]},#{@city.name}").first
      @city_lat_lng = [geo.data['city'], geo.data['latitude'], geo.data['longitude']]
      @bars = Bar.geo_scope(origin: @origin).includes(:swigs).where(conditions.join(" AND ")).where(zip_code: params[:zip_code])
    end

    respond_to do |format|
      format.html
      format.mobile
    end
  end

  def city
    @city = City.find(params[:id])

    conditions = []
    conditions << "swigs.swig_type = '#{params[:swig_type]}'" unless params[:swig_type].blank?
    conditions << "bars.sports_team LIKE '%#{params[:sports_team]}%'" unless params[:sports_team].blank?
    conditions << "swigs.swig_day = '#{Time.zone.now.strftime("%A").to_s}'"

    @origin = params[:zip_code].blank? ? [@city.latitude, @city.longitude] : params[:zip_code]

    unless params[:radius].blank?
      @bars = Bar.within(params[:radius].to_i, origin: @origin).includes(:swigs).where(conditions.join(" AND ")).where(city: @city.name).order("swig_type DESC")
    else
      @bars = Bar.geo_scope(origin: @origin).includes(:swigs).where(conditions.join(" AND ")).where(city: @city.name).order("swig_type DESC")
    end

    unless params[:zip_code].blank?
      geo = Geocoder.search("#{params[:zip_code]},#{@city.name}").first
      @city_lat_lng = [geo.data['city'], geo.data['latitude'], geo.data['longitude']]
      @bars = Bar.geo_scope(origin: @origin).includes(:swigs).where(conditions.join(" AND ")).where(zip_code: params[:zip_code]).order("swig_type DESC")
    end
  end

  def contact_us
    @new_contact = Contact.new
  end

  def contact_us_for_homepage
    @new_contact = Contact.new
  end

  def create_contact_us
    @new_contact = Contact.new(params[:contact])

    if @new_contact.save
      redirect_to :back, notice: "send contact success"
    else
      redirect_to :back, notice: "send contact fail"
    end
  end

  def bars_list_to_swig
    conditions = ["swigs.swig_day = '#{Time.zone.now.strftime("%A").to_s}'"]

    @bars = Bar.within(@valid_radius_for_swigging, origin: [@city_lat_lng[1], @city_lat_lng[2]], order: "distance DESC").
      includes(:swigs).where(conditions.join(" AND ")).sort_by_distance_from([@city_lat_lng[1], @city_lat_lng[2]])
    
  end

  def mobile_dashboard; end

  def sign_out_turning_point; end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_contact_us_form_partial.html.erb
<div class="modal-header">
  <a class="close" data-dismiss="modal"><b>x</b></a>
  <h3>Contact Us</h3>
</div>
<%= simple_form_for(@new_contact, url: create_contact_us_home_path, html: { :class => "form-horizontal"}) do |f| %>
  <div class="modal-body well">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :message, input_html: {style: "width: 280px;height: 150px;"} %>
  </div>
  <div class="modal-footer">
    <%= f.submit "Send", class: "btn-primary pull-right"%>
    </div>
  <% end %>

app/views/home/bars_list_to_swig.mobile.erb
<div data-role="page" id="swig_list_page" onclick="initialize()">
  <div data-role="header" style="text-align: center;">
    <%= render partial: "shared/swigbig_logo" %>
    <div data-role="controlgroup" style="margin: 5px;width: 100%;">
      <h3>Select your Bar:</h3>
    </div>
  </div>

  <div data-role="content" >
    <table class="zebra-striped">
      <th>Bar Name</th>
      <th>Distance</th>
      <tbody id="main_swigs_list">
        <% @bars.each do |bar| %>
          <tr>
            <td><a onclick="window.location.href='<%= users_bar_profile_url(bar,:mobile) %>'"><%= bar.name %></a></td>
            <td><%=  begin
                sprintf("%.2f",Geocoder::Calculations.distance_between([@city_lat_lng[1].to_f, @city_lat_lng[2].to_f], [bar.latitude, bar.longitude]))
              rescue
              end %> miles</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div><!-- /content -->

  <div data-role="footer" data-position="fixed" style="width: 100%">
    <div data-role="controlgroup" style="margin: 5px;width: 97%;">
      <a data-role="button" style="width: 100%;margin: 5px;" class="btn-primary" onclick="window.location.href='<%= main_home_path(:mobile)%>'" >CANCEL</a>
      <%= render partial: "shared/footer_menu_partial" %>
    </div>
  </div><!-- /footer -->
</div>

app/views/home/main.mobile.erb
<style type="text/css">
  #map_home_canvas { height: 325px ; width: 100%;}
</style>
<style type="text/css">
  .string{margin-left: -80px;}
  .select{margin-left: -80px;}
</style>
<script type="text/javascript"
        src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBaz4HYWs-2If2J6Awpc23Twds3i-1Mj88&sensor=false">
</script>
<script type="text/javascript">
  var condition = true
  function initialize() {
    if (condition){
      condition = false;
      var myOptions = {
        zoom: 13,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      var map = new google.maps.Map(document.getElementById("map_home_canvas"), myOptions);
<% if @origin.class.eql?(String) %>
        var geocoder = new google.maps.Geocoder();
        geocoder.geocode( {'address': '<%= @origin %>'}, function(results, status) {
          map.setCenter(results[0].geometry.location);
        });
<% else %>
        map.setCenter(new google.maps.LatLng(<%= @origin.first %>, <%= @origin.last %>));
        var image = "<%= "/assets/user_blue.png" %>";
        var marker = new google.maps.Marker({
          position: new google.maps.LatLng(<%= @origin.first %>, <%= @origin.last %>),
          map: map,
          icon: image,
          title: "User"
        });
<% end %>

      var bar = [];
<% @bars.each do |b| %>
        var x = [];
        x.push(<%= b.latitude rescue nil %>);//0
        x.push(<%= b.longitude rescue nil %>);//1
        x.push('<%= b.id rescue nil %>');//2
        x.push('<%=j link_to  b.name, bar_profile_path(b) rescue nil %>');//3
        x.push('<%= n_line(b.swigs.standard.today.first.deal) rescue nil %>');//4
  <% b.swigs.today.big.order('people ASC').each do |b_swig| %>
          x.push('<%= b_swig.deal rescue nil %>');//5++
          x.push('<%= b_swig.people rescue nil %>');
  <% end %>
        bar.push(x);
        /*
                     x.push(<%#= b.latitude rescue nil %>);//0
                    x.push(<%#= b.longitude rescue nil %>);//1
                    x.push('<%#= b.id rescue nil %>');//2
                    x.push('<%#=j link_to  b.name, bar_profile_path(b) rescue nil %>');//3
                    x.push('<%#= n_line(b.swigs.standard.today.first.deal) rescue nil %>');//4
                    x.push('<%#= b.sports_team.gsub(",", "<br/>").html_safe rescue nil %>');//5
                    x.push('<%#= n_line(b.swigs.today.lock_status_active.first.deal) rescue "No Swig Today" %>');//6
                    x.push('<%#= b.swigs.today.first.lock_status rescue nil %>');//7
                    x.push('<%#= b.swigs.today.first.people rescue nil %>');//8
  <%# b.swigs.today.big.each do |b_swig| %>
                      x.push('<%#= b_swig.deal rescue nil %>');//9++
                      x.push('<%#= b_swig.people rescue nil %>');
  <%# end %>
         */

<% end %>

      function addInfoWindow(marker, newMarker){
        var infowindow = new google.maps.InfoWindow({
          content: newMarker.info
        });
        google.maps.event.addListener(marker, 'click', function() {
          infowindow.open(map,marker);
        });
      }

      var infowindow = new google.maps.InfoWindow();

      for (var i = 0; i < bar.length; i++) {
        var marker = new google.maps.Marker({
          position: new google.maps.LatLng(bar[i][0], bar[i][1]),
          map: map
        });

        var htmlcontent = '<div style="height: 120;width: 120px;border-radius: 5px"><b>'+bar[i][2]+'</b>'+'<br/>'+bar[i][3]+'</div>';

        google.maps.event.addListener(marker, 'click', (function(marker, i) {
          return function() {
            if (bar[i][5] == "unlock"){
              var lock_status =  '<%= image_tag("/assets/Unlock-icon.png", style: "height: 30px;") %>'
            }else{
              var lock_status =  '<%= image_tag("/assets/Lock-icon.png", style: "height: 30px;") %>'
            };

            infowindow.setContent('<h4>'+bar[i][3]+'</h4>'
              +'<div class="span3 pull-left well">'+bar[i][4]+'</div>'
              +'<div class="span3">'+'<b>BigSwig</b><br/>'
              +bar[i][5]+'<br/><b>req: </b>'+bar[i][6]+'<br/>'
              +bar[i][7]+'<br/><b>req: </b>'+bar[i][8]+'<br/>'
              +bar[i][9]+'<br/><b>req: </b>'+bar[i][10]+'<br/>'
              +'</div>'
            /*
              +lock_status+'<b>req: </b>'+bar[i][8]+'</div>'
              +'<div class="span2"><b>Sports Teams</b><br/>'+bar[i][5]+'</div>'
             infowindow.setContent('<h4>'+bar[i][3]+'</h4>'
              +'<div class="span3 pull-left well">'+bar[i][4]+'</div>'
              +'<div class="span3">'+'<b>BigSwig</b><br/>'
              +bar[i][9]+'<br/><b>req : </b>'+bar[i][10]+'<br/>'
              +bar[i][11]+'<br/><b>req : </b>'+bar[i][12]+'<br/>'
              +bar[i][13]+'<br/><b>req : </b>'+bar[i][14]
              +'</div>'
             */

          );
            infowindow.open(map, marker);
          }
        })(marker, i));
      }
    }
  }
</script>

<div data-role="page" id="swig_list_page" onclick="initialize()">
  <div data-role="header" data-position="fixed" style="text-align: center;">
    <%= render partial: "shared/swigbig_logo" %>
    <div data-role="controlgroup" style="margin: 5px;width: 100%;">
      <div data-role="controlgroup" data-type="horizontal" style="margin: 5px;width: 100%;">
        <a href="#" data-toggle="tab" data-role="button" style="width: 49%;color: white;">List</a>
        <a href="#bars_map_page" data-toggle="tab" onclick="initialize()" data-role="button" style="width: 47%;color: white;">Map</a>
      </div>
      <a href="#filter_page" data-role="button" style="color: white;width: 97%;border-radius: 3px;">Filter</a>
    </div>
  </div>

  <div data-role="content" style="margin-bottom: 80px;">
    <table class="zebra-striped">
      <!--<a onclick="window.location.href='<%#= users_mobile_invite_fb_friends_url(16,:mobile) %>'">Invite test</a>-->

      <th>Bar Name</th>
      <th>Distance</th>
      <tbody id="main_swigs_list">
      <b><%= @bars.blank? ? "No Bar in #{@radius_to_show_in_mobile_list}.miles radius" : "" %></b>
      <% @bars.each do |bar| %>
        <tr>
          <td><a onclick="window.location.href='<%= users_bar_profile_url(bar,:mobile) %>'"><%= bar.name %></a></td>
          <td><%=  begin
              sprintf("%.2f",Geocoder::Calculations.distance_between([@city_lat_lng[1].to_f, @city_lat_lng[2].to_f], [bar.latitude, bar.longitude]))
            rescue
            end %> miles</td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div><!-- /content -->

  <div data-role="footer" data-position="fixed" style="width: 100%">
    <div data-role="controlgroup" style="margin: 5px;width: 97%;">
      <% if user_signed_in? %>
        <a data-role="button" onclick="window.location.href='<%= bars_list_to_swig_home_url(:mobile) %>'"  style="width: 100%;">Swig!</a>
      <% end %>
      <%= render partial: "shared/footer_menu_partial" %>
    </div>
  </div><!-- /footer -->
</div><!-- /page one -->


<!-- Start of second page: #bar map -->
<div data-role="page" id="bars_map_page" onclick="initialize()">
  <div data-role="header" data-position="fixed" style="text-align: center;">
    <%= render partial: "shared/swigbig_logo" %>
    <div data-role="controlgroup" style="margin: 5px;width: 100%;">
      <div data-role="controlgroup" data-type="horizontal" style="margin: 5px;width: 100%;">
        <a href="#swig_list_page" data-role="button" style="width: 49%;color: white;">List</a>
        <a href="#" data-role="button" style="width: 49%;color: white;">Map</a>
      </div>
      <a href="#filter_page" data-role="button" style="color: white;width: 97%;border-radius: 3px;">Filter</a>
    </div>
  </div>

  <div data-role="content" >
    <div id="map_home_canvas"></div>
  </div><!-- /content -->

  <div data-role="footer" data-position="fixed" style="width: 100%">
    <% if user_signed_in? %>
      <a data-role="button" onclick="window.location.href='<%= bars_list_to_swig_home_url(:mobile) %>'"  style="width: 100%;">Swig!</a>
    <% end %>
    <%= render partial: "shared/footer_menu_partial" %>
  </div><!-- /footer -->
</div>

<div data-role="page" id="filter_page">
  <div data-role="header" data-position="fixed" style="text-align: center;">
    <%= render partial: "shared/swigbig_logo" %>
    <div data-role="controlgroup" style="margin: 5px;width: 100%;">
      <div data-role="controlgroup" data-type="horizontal" style="margin: 5px;width: 100%;">
        <a href="#swig_list_page" data-role="button" style="width: 49%;color: white;">List</a>
        <a href="#bars_map_page" data-toggle="tab" onclick="initialize()" data-role="button" style="width: 47%;color: white;">Map</a>
      </div>
      <a href="#filter_page" data-role="button" style="color: white;width: 97%;border-radius: 3px;">Filter</a>
    </div>
  </div>

  <div data-role="content" >
    <%= simple_form_for(:search, url: root_path) do |f|%>
      <%= text_field_tag :zip_code, params[:zip_code], placeholder: "Zip Code", style: "height: 30px;" %>
      <b style="margin-left: 60px;">Radius in Mile</b>
      <%= select_tag(:radius, options_for_select(GeoRadius.all.collect {|b| [ b.radius, b.radius]}.unshift(["any"]), params[:radius])) %>
      <br/>
      <br/>
      <b style="margin-left: 60px;">Swig Type</b>
      <%= select_tag :swig_type, options_for_select([["any",""], ["Standard","Standard"],["Big","Big"]], params[:swig_type]) %>
      <b style="margin-left: 60px;">Sports teams</b>
      <%= select_tag :sports_team, options_for_select(sport_teams_collection.unshift("any"), params[:sports_team]) %>
      <div style="display: none;">
        <%= f.submit "Search", class: "btn-mini btn-primary pull-right", style: "margin: 10px;", id: "search_btn" %>
        </div>
      <% end %>
      <a  data-role="button" onclick="$('#search_btn').click()" style="width: 100%;margin: 5px;" >Search!!</a>
    </div>

    <div data-role="footer" data-position="fixed" style="width: 100%">
      <%= render partial: "shared/footer_menu_partial" %>
    </div>
  </div>