config/routes.rb
Swprototype::Application.routes.draw do
  get "home/index"

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  constraints(Subdomain) do
    root to:  "bar_home#index"
    match "/" => "bar_home#index", as: "bar_home"
    devise_scope :bar do
      match "/sign_in" => "bars/sessions#new", :as => :sign_in_bars
      match "/sign_up" =>  "bars/registrations#new", :as => :sign_up_bars
    end
  end

  root to:  "home#main"
  
  match "bars/city/:id" =>  "home#city", as: "city"
  get "live_swig_feed" =>  "request#live_swig_feed", as: "live_swig_feed"
  get "set_time_zone" =>  "application#set_time_zone", as: "set_time_zone"

  resource :home do
    collection do
      get "main" =>  "home#main", as: "main"
      get "contact_us" =>  "home#contact_us", as: "contact_us"
      get "contact_us_for_homepage" =>  "home#contact_us_for_homepage", as: "contact_us_for_homepage"
      post "create_contact_us" =>  "home#create_contact_us", as: "create_contact_us"
      get "bars_list_to_swig" =>  "home#bars_list_to_swig", as: "bars_list_to_swig"
      get "mobile_dashboard" =>  "home#mobile_dashboard", as: "mobile_dashboard"
      match "sign_out_turning_point" =>  "home#sign_out_turning_point", as: "sign_out_turning_point"
    end
  end

  resource :request do 
    collection do
      match "invitations" =>  "request#invitations", as: "invitations"
      post "create_request" =>  "request#create_request", as: "create_request"
      match "welcome" =>  "request#welcome", as: "welcome"
      post "login_to_swigbig" =>  "request#login_to_swigbig", as: "login_to_swigbig"
      match "login" =>  "request#login", as: "login"
      match "select_type" =>  "request#select_type", as: "select_type"
    end
  end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", confirmations: "users/confirmations",passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}
  devise_scope :user do
    post "/update_picture_from_facebook" => "users/omniauth_callbacks#update_picture_from_facebook", :as => :update_picture_from_facebook
  end

  get "bar/:bar_id" => "users/bars#show", as: "bar_profile"
  
  resource :users do
    collection do
    end
  end
  
  devise_for :bars, controllers: {registrations: "bars/registrations", sessions: "bars/sessions", confirmations: "bars/confirmations", passwords: "bars/passwords"}

  devise_for :members, controllers: {registrations: "members/registrations"}
  
  namespace :bars do
    get "delete_swig/:id" => "dashboard#delete_swig", as: "delete_swig"
    match  "invite_friend" => "dashboard#after_join_invite_friends", as: "after_join_invite_friends"
    post  "invite_friend_by_email" => "dashboard#invite_friend_by_email", as: "invite_friend_by_email"
    match  "sport_lists" => "dashboard#sport_lists", as: "sport_lists"
    match  "users_lists" => "dashboard#users_lists", as: "users_lists"
    match  "completion" => "dashboard#completion", as: "completion"
    post  "update_completion" => "dashboard#update_completion", as: "update_completion"
    match  "second_completion" => "dashboard#second_completion", as: "second_completion"
    post  "update_second_completion" => "dashboard#update_second_completion", as: "update_second_completion"
    match  "dashboard" => "dashboard#index", as: "dashboard"
    match  "product" => "products#index", as: "product"
    post  "create_reward_message/:user_id/:winner_id" => "dashboard#create_reward_message", as: "create_reward_message"
    post  "create_swig" => "dashboard#create_swig", as: "create_swig"
    post  "create_big_swig" => "dashboard#create_big_swig", as: "create_big_swig"
    post  "update_big_swig" => "dashboard#update_big_swig", as: "update_big_swig"
    get  "delete_big_swig/:ids" => "dashboard#delete_big_swig", as: "delete_big_swig"
    post  "update_swig/:id" => "dashboard#update_swig", as: "update_swig"
    post  "create_loyalty" => "dashboard#create_loyalty", as: "create_loyalty"
    post  "create_popularity" => "dashboard#create_popularity", as: "create_popularity"
    get "edit_loyalty/:id" => "dashboard#edit_loyalty", as: :edit_loyalty
    get "new_loyalty" => "dashboard#new_loyalty", as: :new_loyalty
    get "edit_popularity/:id" => "dashboard#edit_popularity", as: :edit_popularity
    get "new_popularity" => "dashboard#new_popularity", as: :new_popularity
    post  "update_loyalty/:id" => "dashboard#update_loyalty", as: "update_loyalty"
    post  "update_popularity/:id" => "dashboard#update_popularity", as: "update_popularity"
    delete  "delete_loyalty/:id" => "dashboard#delete_loyalty", as: "delete_loyalty"
    delete  "delete_popularity/:id" => "dashboard#delete_popularity", as: "delete_popularity"
    get "rewards/index"
    match "rewards" => "rewards#index", as: "rewards"
    post "create_bar_message" => "dashboard#create_bar_message", as: "create_bar_message"
    post  "create_gift" => "dashboard#create_gift", as: "create_gift"
    post  "activate_loyalty/:loyalty_id" => "dashboard#activate_loyalty", as: "activate_loyalty"
    post  "deactivate_loyalty/:loyalty_id" => "dashboard#deactivate_loyalty", as: "deactivate_loyalty"
    post  "activate_popularity/:popularity_id" => "dashboard#activate_popularity", as: "activate_popularity"
    post  "deactivate_popularity/:popularity_id" => "dashboard#deactivate_popularity", as: "deactivate_popularity"
    post  "update_gift/:gift_id" => "dashboard#update_gift", as: "update_gift"
    get  "destroy_gift_in_list/:gift_id" => "dashboard#destroy_gift_in_list", as: "destroy_gift_in_list"
    post  "add_bigswig_list" => "dashboard#add_bigswig_list", as: "add_bigswig_list"
    post  "add_bigswig_list_on_update" => "dashboard#add_bigswig_list_on_update", as: "add_bigswig_list_on_update"
    post  "add_bar_hours" => "dashboard#add_bar_hours", as: "add_bar_hours"
    post  "add_bar_hours_on_edit" => "dashboard#add_bar_hours_on_edit", as: "add_bar_hours_on_edit"
    post  "add_reward_to_list" => "dashboard#add_reward_to_list", as: "add_reward_to_list"
    get  "destroy_bar_big_swig_list/:bigswiglist_id" => "dashboard#destroy_bar_big_swig_list", as: "destroy_bar_big_swig_list"
    post  "update_bar_big_swig_list/:bigswiglist_id" => "dashboard#update_bar_big_swig_list", as: "update_bar_big_swig_list"
    post  "search_redeem_code/:code" => "dashboard#search_redeem_code", as: "search_redeem_code"
    get  "swiger_list" => "dashboard#swiger_list", as: "swiger_list"
    post  "update_bar_hours" => "dashboard#update_bar_hours", as: "update_bar_hours"
    get  "swigger_total_count" => "dashboard#swigger_total_count", as: "swigger_total_count"
    get "reward_stats" => "dashboard#reward_stats", as: :reward_stats

    resources :messages do
      collection do
        get  "notify_mark_all_read" => "messages#notify_mark_all_read", as: "notify_mark_all_read"
        get  "messages_mark_all_read" => "messages#messages_mark_all_read", as: "messages_mark_all_read"
        get 'notifications'
        get 'sent'
        post 'custom_action(/:form_type)' => "messages#custom_action", as: :custom_action
        get 'trash'
        get 'message_popup'
        get 'new/:user_ids' => "messages#new", as: :new
        post 'reply_message'

      end
    end

  end
  
  resources :bars do
    match "upgrade" => "bars/payment_gateway#index", as: "upgrade"
  end

  namespace :users do
    match  "invite_friend" => "dashboard#after_join_invite_friends_by_email", as: "after_join_invite_friends_by_email"
    match  "invite_friends" => "dashboard#after_join_invite_friends_by_fb", as: "after_join_invite_friends_by_fb"
    post  "invite_friend_by_email" => "dashboard#after_sign_up_invite_friend_by_email", as: "after_sign_up_invite_friend_by_email"
    post  "invite_friend_by_fb" => "dashboard#after_sign_up_invite_friend_by_fb", as: "after_sign_up_invite_friend_by_fb"
    post  "update_user_for_mobile" => "dashboard#update_user_for_mobile", as: "update_user_for_mobile"
    match  "completion" => "dashboard#completion", as: "completion"
    post  "update_completion" => "dashboard#update_completion", as: "update_completion"
    match  "notifications" => "notifications#index", as: "notifications"
    match  "user_dashboard" => "dashboard#index", as: "dashboard"
    match  "facebook_dashboard" => "dashboard#facebook_page", as: "facebook_page"
    match  "facebook_mobile_profile" => "dashboard#facebook_mobile_profile", as: "facebook_mobile_profile"
    match  "facebook_update_status" => "dashboard#facebook_update_status", as: "facebook_update_status"
    match  "invite_swigbig" => "dashboard#invite_swigbig", as: "invite_swigbig"
    post "invite_by_email" => "dashboard#invite_by_email", as: :invite_by_email
    match  "profile/:id" => "dashboard#show", as: "profile"
    match  "rewards" => "dashboard#rewards", as: "rewards"
    match  "update_account" => "dashboard#update_account", as: "update_account"
    match  "update_password" => "dashboard#update_password", as: "update_password"
    get  "show_swig/:bar_id/:swig_id" => "bar_swigs#show_swig", as: "show_swig"
    post  "enter_bar/:bar_id" => "bar_swigs#enter_bar", as: "enter_bar"
    post  "redeem/:bar_id" => "bars#redeem_reward", as: "redeem_reward"
    post "create_popularity/:bar_id" => "bars#create_popularity", as: "create_popularity"
    match "friendship" => "friends#index", as: "friend_index"
    post "friend_request/:id" => "friends#friend_request", as: "friend_request"
    post "remove_friend/:id" => "friends#remove_friend", as: :remove_friend
    post "approve_friend/:id" => "friends#approve_friend", as: :approve_friend
    get  "swiger_list/:bar_id" => "bars#swiger_list", as: "swiger_list"
    get  "mobile_reward" => "dashboard#mobile_reward", as: "mobile_reward"
    get  "lock_post_event" => "dashboard#lock_post_event", as: "lock_post_event"
    get  "unlock_post_event" => "dashboard#unlock_post_event", as: "unlock_post_event"

app/models/bar.rb
require 'geokit'
require 'geokit-rails3'
include GeoKit::Geocoders
class Bar < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:omniauthable,
  :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :address,
    :zip_code, :phone_number, :city, :state, :country, :latitude, :longitude, :logo, :slug,
    :status, :qrcode, :plan_id, :service_uid, :terms, :bar_background, :sports_team, :website_link,
    :facebook_link, :twitter_link, :google_plus_link, :bar_phone, :bar_description, :bar_hour,
    :bar_hours_attributes, :full_address, :sports_team_list, :lock_status
  
  validates :terms, :acceptance => true
  validates :address, :zip_code, :city, :presence => true, :on => :update
  #  validates :zip_code, format: {:with => /^\d{5}(-\d{4})?$/, :message => "should be in the form 12345 or 12345-1234"}, :on => :update

  before_update  :set_http_website
  before_validation :set_full_address, :locate

  geocoded_by :address

  extend  FriendlyId
  friendly_id :name , use: :slugged
  
  acts_as_taggable_on :sports_teams
  acts_as_messageable required: [:topic, :body, :received_messageable_id]
  
  with_options dependent: :destroy do |bar|
    bar.has_many :bar_hours
    bar.has_many :big_swig_lists
    bar.has_many :gifts
    bar.has_many :swigs
    bar.has_many :swigers
    bar.has_many :products
    bar.has_many :points
    bar.has_many :popularity_inviters
    bar.has_many :winner_rewards
    bar.has_many :winners
    bar.has_one :loyalty
    bar.has_one :popularity
  end

  accepts_nested_attributes_for :bar_hours, :allow_destroy => true
  
  acts_as_mappable :default_units => :miles,
    :default_formula => :sphere,
    :distance_field_name => :distance,
    :lat_column_name => :latitude,
    :lng_column_name => :longitude

  def set_full_address
    unless self.address.blank?
      self.full_address = "#{self.address},#{self.city},#{self.zip_code}, United States"
    end
  end

  def locate
    unless self.address.blank? 
      loc = MultiGeocoder.geocode(set_full_address)
      if loc.success
        self.latitude = loc.lat
        self.longitude = loc.lng
      end
    end
  end

  def set_http_website
    self.website_link = "http://#{self.website_link}" if !self.website_link.blank? and !self.website_link.include?("http://")
    self.facebook_link = "http://#{self.facebook_link}" if !self.facebook_link.blank? and !self.facebook_link.include?("http://")
    self.twitter_link = "http://#{self.twitter_link}" if !self.twitter_link.blank? and !self.twitter_link.include?("http://")
    self.google_plus_link = "http://#{self.google_plus_link}" if !self.google_plus_link.blank? and !self.google_plus_link.include?("http://")
  end

end

app/controllers/bars/confirmations_controller.rb
class Bars::ConfirmationsController < Devise::ConfirmationsController
  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    bars_dashboard_url
  end
end

app/controllers/bars/gifts_controller.rb
class Bars::GiftsController < ApplicationController

  def destroy
    gift = Gift.find(params[:id])
    gift.destroy
   redirect_to bars_dashboard_url, notice: "Reward delete successfully!"
  end

  def remove_gift
    fewf
  end
end

app/controllers/bars/omniauth_callbacks_controller.rb
class Bars::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
end

app/controllers/bars/passwords_controller.rb
class Bars::PasswordsController < Devise::PasswordsController
  layout "bars"
  
end

app/controllers/bars/payment_gateway_controller.rb
class Bars::PaymentGatewayController < ApplicationController
  layout "main_bars"

  def index; end
end

app/controllers/bars/products_controller.rb
class Bars::ProductsController < ApplicationController
  layout "bars"

  def index
    @bar = current_bar
    @swig = @bar.swigs.new
    @swigs = @bar.swigs
    @product = @bar.products.new
    @products = @bar.products
  end
  
end

app/controllers/bars/registrations_controller.rb
class Bars::RegistrationsController < Devise::RegistrationsController
  layout "bars"
  
  def after_update_path_for(resource)
    bars_completion_url
  end

  def after_sign_up_path_for(resource)
    session[:request_user_privilage] = true
    
    if current_bar.address.blank?
      AdminUser.first.send_message(current_bar, {topic: "Welcome to SwigBIG", body: "#{current_bar.name} is not yet listed! <a href='/bars/completion'>Please complete your profile</a>", category: 22})
      bars_dashboard_url
    else
      bars_dashboard_url
    end
  end

  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)

    if current_bar.update_attributes(params[:bar])
      sign_in current_bar, :bypass => true
      redirect_to bars_dashboard_url, notice: "Update Success!"
    else
      render action: :edit, notice: "field with * mark must filled!"
    end
  end

  def edit
    @bar_hours = current_bar.bar_hours.order("id").group_by {|hour| "#{hour.open_time} - #{hour.close_time}" }
    @counter = BarHour::DAY_LIST[@bar_hours.to_a.last.last.last.day] rescue 0
    
    render :edit
  end
  
end

app/controllers/bars/rewards_controller.rb
class Bars::RewardsController < ApplicationController
  layout "bars"

  def index
    @bar = current_bar
    @loyalty = @bar.rewards.where(reward_type: "Loyalty")
    @popularity = @bar.rewards.where(reward_type: "Popularity")
  end
  
end

app/controllers/bars/sessions_controller.rb
class Bars::SessionsController < Devise::SessionsController
  layout "bars"

  def create
    session[:request_user_privilage] = true

    resource = warden.authenticate!(auth_options)

    if resource.lock_status.eql?(false)

      set_flash_message(:notice, :signed_in) if is_navigational_format?
      sign_in(resource_name, resource)
      respond_with resource, :location => after_sign_in_path_for(resource)
      
    elsif resource.lock_status.eql?(true)

      redirect_path = after_sign_out_path_for(resource_name)
      signed_out = sign_out(current_bar)
      flash[:notice] = "Your Account locked!"

      respond_to do |format|
        format.any(*navigational_formats) { redirect_to redirect_path }
        format.all do
          head :no_content
        end
      end

    end
  end

  def after_sign_in_path_for(resource)
    bars_dashboard_url
  end
  
end

app/views/bars/dashboard/_big_swig_list_to_delete_or_update.html.erb
<table>
  <% @big_swig_lists.each do |bigswig| %>
    <tr>
      <td><%= bigswig.big_swig %></td>
      <td><%= link_to "<i class='icon-remove pull-right'></i>".html_safe, bars_destroy_bar_big_swig_list_path(bigswig.id), confirm: "Are you sure you want to Delete the following BIG swig? #{bigswig.big_swig}".html_safe %></td>
      <td><a class="" data-toggle="modal" href="#edit_swigbiglist<%= bigswig.id %>" data-dismiss="modal">Edit</a></td>
      <%= content_for :outer do %>
      <div id="edit_swigbiglist<%= bigswig.id %>" class="modal hide fade" >
        <%= render partial: "edit_form_bigswig_list", locals: {bigswig: bigswig} %>
      </div>
    <% end %>
  </tr>
<% end %>
</table>

app/views/bars/dashboard/_bigswig_list.html.erb
<%= select_tag "deals[]", options_for_select(bigswig_collection), {style: "width: 500px;margin-bottom: 3px;"} %>

app/views/bars/dashboard/_swig_list_monday.html.erb
<%#= javascript_include_tag "validate_people" %>
<%= content_for :js_footer do %>
<script type="text/javascript">
  function monday_clear_list(){
    $("#monday_notice_lists").text("")
  }
  function show_list(){
    $("#add_biglist").text("")
  }
  function monday_done(){
    $('#mon_done').attr('disabled', 'disabled');
    $("#monday_done").click()
  }
  function validate_monday_standard_swig(){
    if($("#monday_standard_swig textarea").val() == ''){
      $("#monday_standard_swig textarea").css('border', '1px solid red');
      $("#monday_standard_text_notification").text('Standard Swig must fill!');
      valid_monday_swig = false;
    }else{
      $("#monday_standard_swig textarea").css('border', '1px solid black');
      valid_monday_swig = true;
    }
    if(valid_monday_swig){
      $('#goto_create_monday_swig').click();
      $('#goto_create_monday_swig').remove();
    }
  }
  
</script>
<% end %>


<% unless @swigs_monday.standard.blank? %>
  <% @swigs_monday.standard.each do |swig|%>
    <h4>Standard Swig</h4>
    <div class="span8 pull-left">
      <%= n_line(swig.deal) rescue nil %>
    </div>
    <div class="span2 pull-left">
      <a href="#edit_monday_standard_swig<%= swig.id %>" data-toggle="modal" ><b>Update</b></a>
    </div>
    <%= content_for :outer do %>
      <div id="edit_monday_standard_swig<%= swig.id %>" class="modal hide fade">
        <div class="modal-header">
          <a class="close" data-dismiss="modal"><b>x</b></a>
          <h4>Standard Swig on Monday</h4>
        </div>
        <div class="modal-body well">
          <%= simple_form_for(Swig.find(swig.id), url: bars_update_swig_path(swig.id), method: :post, html: { :class => "form-horizontal"} ) do |f| %>
            <%= f.input :deal, as: :text, :label => false, input_html: { style: "width: 300px;height: 100px" } %>
            <div class="form-actions">
              <%= f.submit "Update Swig", class: "btn-primary" %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>

  <% else %>
    <h4>Standard Swig</h4>
    <div class="span10">
      <p>Your Standard Swigs have not been setup for this day</p>
      <br/>
      <a href="#monday_standard_swig" data-toggle="modal" >Set them up now?</a>
    </div>
  <% end %>
  <div class="clearfix"></div>
  <% unless @swigs_monday.big.blank? %>
    <h4>Big Swig</h4>
    <div class="span2 pull-left">
      <a href="#update_monday_big_swig" data-toggle="modal" >Update</a>
    <%#= link_to "Delete", bars_delete_big_swig_path(@swigs_monday.big.pluck(:id)) %>
    </div>
    <div class="clearfix"></div>
    <br/>
    <% @swigs_monday.big.order("people ASC").each do |swig|%>
      <div class="clearfix"></div>
      <div class="span1">
        <%= swig.lock_status.blank? ? image_tag("/assets/Lock-icon.png", style: "height: 30px;") : image_tag("/assets/Unlock-icon.png", style: "height: 30px;") %>
      </div>
      <div class="span7 pull-left">
        <% if swig.swig_type.eql?("Big") %>
          <%= swig.deal %>
        <% elsif %>
          <%= n_line(swig.deal) %>
        <% end %>
      </div>
      <div class="span2 pull-right">
        <% if Time.zone.now.strftime('%A').eql?('Monday') %>
          <%= current_bar.swigers.today.count %><b>/</b><%= swig.people %>
        <% else %>
          0<b>/</b><%= swig.people %>
        <% end %>
      </div>
      <div class="clearfix"></div>
      <br/>
    <% end %>
  <% else %>
    <h4>Big Swig</h4>
    <a href="#monday_big_swig" data-toggle="modal" >Set them up now?</a>
  <% end %>


  <%= content_for :outer do %>
    <div id="monday_standard_swig" class="modal hide fade">
      <div class="modal-header">
        <a class="close" data-dismiss="modal"><b>x</b></a>
        <h4>Standard Swig on Monday</h4>
      </div>
      <div class="modal-body well">
        <div id="monday_standard_text_notification" style="color: red;"></div>
        <%= simple_form_for(@swig, url: bars_create_swig_path, html: { :class => "form-horizontal", id: "monday_standard"}) do |f| %>
          <%= f.input :swig_type, as: :hidden, input_html: {value: "Standard"} %>
          <%= f.input :swig_day, as: :hidden, input_html: {value: "Monday"} %>
          <%= f.input :deal, as: :text, :label => false, input_html: { style: "width: 300px;height: 100px", id: "monday_standard_swig" }, required: true, include_blank: false %>
        </div>
        <div class="modal-footer">
          <a class="close" data-dismiss="modal"><b></b></a>
          <%= f.submit "Done", id: "goto_create_monday_swig", style: "display: none;" %>
          <a id="buttonID" class="btn btn-primary" onclick="return validate_monday_standard_swig()" id="">Create</a>
          </div>
        <% end %>
      </div>


      <div id="monday_big_swig" class="modal hide fade">
        <div class="modal-header">
          <a class="close" data-dismiss="modal"><b>x</b></a>
          <h4>Pick your Big Swig for Monday</h4>
        </div>
        <div class="modal-body well">
          <div id="people_text"></div>
          <%= simple_form_for(:swig, url: bars_create_big_swig_path, html: { :class => "form-horizontal"}) do |f| %>
            <% 3.times do |x| %>
              <div id="monday_bigswig_lists<%= x + 1 %>">
                <%= render partial: "bigswig_list" %>
              </div>
              <div id="people_warning_text_<%= "0_#{x}" %>" style="display: none;">people require must fill!</div>
              <%= number_field_tag "peoples[0][#{x}]",nil, class: "positive" %>
                <%= hidden_field_tag "day", 0 %>
                <br/>
                <br/>
              <% end %>
              <%= hidden_field_tag :swig_type, "Big" %>
              <%= hidden_field_tag :swig_day, "Monday" %>
              <!--<div class="modal-footer">-->
              <%= f.submit "Done", class: "btn-primary pull-right", style: "margin-bottom: -100px;display: none;", id: "monday_done" %>
              <% end %>
              <h5 style="text-align: center;">OR</h5>
              <div class="clearfix"></div>
              <!--<div id="monday_notice_lists" style="color: green;"></div>-->
              <b><div class="add_bigswig_text" style="color: green;display: none;">BigSwig was added successfully!</div></b>
              <%= simple_form_for(:big_swig_list, url: bars_add_bigswig_list_path, html: {:class => "form-horizontal", remote: true}) do |f| %>
                <div style="text-align: center;margin-bottom: 15px;">
                  <b>Create bigswig list</b>
                </div>
                <div style="margin-bottom: -25px;margin-left: 425px;">
                  <%= f.submit "Add you own..", class: "btn-success",style: "margin-top: -50px;", onclick: "monday_clear_list()" %>
                  </div>
                  <div style="margin-left: -160px;">
                    <%= f.input :big_swig, label: false, placeholder: "Type your bigswig here...", input_html: {style: "width: 400px;", class: "bigswig_input_box"}, required: true %>
                  <% end %>
                </div>
                <!--</div>-->
                <div class="modal-footer">
                  <a class="btn btn-primary" onclick="return validatePeople(0, 'mon_done', 'new')">Done</a>
                  <a class="btn btn-primary" id="mon_done" onclick="monday_done(this)" style="display: none;">Done</a>
                </div>
              </div>
            </div>

            <div id="update_monday_big_swig" class="modal hide fade">
              <div class="modal-header">
                <a class="close" data-dismiss="modal"><b>x</b></a>
                <h4>Update Big Swig on Monday</h4>
              </div>
              <div class="modal-body well">

                <%= simple_form_for(:swig, url: bars_update_big_swig_path, html: { :class => "form-horizontal"}) do |f| %>
                  <% @swigs_monday.big.order("people").each_with_index do |swig, x|%>
                    <%= hidden_field_tag "swig_ids[]", swig.id %>
                    <div id="monday_bigswig_lists_on_update_<%= x %>">
                      <%= render partial: "bigswig_list_on_update", locals: {swig_deal: swig.deal}, :class => "biglist_select"%>
                    </div>
                    <div id="people_update_warning_text_<%= "0_#{x}" %>" style="display: none;">people require must fill!</div>
                    <%= number_field_tag "people[]", swig.people, style: "width: 100px;margin-bottom: 3px;", class: "positive", id: "peoples_update_0_#{x}" %>
                    <% end %>
                  </div>
                  <%= f.submit "Update Swig", class: "btn-primary", style: "display: none;", id: "monday_update_button" %>
                  <% end %>
                  <h5 style="text-align: center;">OR</h5>
                  <div class="clearfix"></div>
                  <%= simple_form_for(:big_swig_list, url: bars_add_bigswig_list_on_update_path, html: {:class => "form-horizontal", remote: true}) do |f| %>
                    <div id="monday_notice_lists" style="color: green;"></div>
                    <div style="text-align: center;margin-bottom: 15px;">
                      <b>Create bigswig list</b>
                    </div>
                    <div style="margin-bottom: -25px;margin-left: 425px;">
                      <%= f.submit "Add you own..", class: "btn-success",style: "margin-top: -50px;", onclick: "monday_clear_list()" %>
                      </div>
                      <div style="margin-left: -150px;">
                        <%= f.input :big_swig, label: false, placeholder: "Type your bigswig here...", input_html: {style: "width: 400px;"} %>
                      <% end %>
                    </div>
                    <div class="modal-footer">
                      <a class="btn btn-primary" onclick="return validatePeople(0, 'mon_update_done', 'update')">Update Swig</a>
                      <a class="btn" onclick="$('#monday_update_button').click();" id="mon_update_done" style="display: none;"></a>
                    </div>
                  </div>
                <% end %>