config/routes.rb
Swprototype::Application.routes.draw do
  get "home/index"

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  constraints(Subdomain) do
    root to:  "bar_home#index"
    match "/" => "bar_home#index", as: "bar_home"
    devise_scope :bar do
      match "/sign_in" => "bars/sessions#new", :as => :sign_in_bars
      match "/sign_up" =>  "bars/registrations#new", :as => :sign_up_bars
    end
  end

  root to:  "home#main"
  
  match "bars/city/:id" =>  "home#city", as: "city"
  get "live_swig_feed" =>  "request#live_swig_feed", as: "live_swig_feed"
  get "set_time_zone" =>  "application#set_time_zone", as: "set_time_zone"

  resource :home do
    collection do
      get "main" =>  "home#main", as: "main"
      get "contact_us" =>  "home#contact_us", as: "contact_us"
      get "contact_us_for_homepage" =>  "home#contact_us_for_homepage", as: "contact_us_for_homepage"
      post "create_contact_us" =>  "home#create_contact_us", as: "create_contact_us"
      get "bars_list_to_swig" =>  "home#bars_list_to_swig", as: "bars_list_to_swig"
      get "mobile_dashboard" =>  "home#mobile_dashboard", as: "mobile_dashboard"
      match "sign_out_turning_point" =>  "home#sign_out_turning_point", as: "sign_out_turning_point"
    end
  end

  resource :request do 
    collection do
      match "invitations" =>  "request#invitations", as: "invitations"
      post "create_request" =>  "request#create_request", as: "create_request"
      match "welcome" =>  "request#welcome", as: "welcome"
      post "login_to_swigbig" =>  "request#login_to_swigbig", as: "login_to_swigbig"
      match "login" =>  "request#login", as: "login"
      match "select_type" =>  "request#select_type", as: "select_type"
    end
  end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", confirmations: "users/confirmations",passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}
  devise_scope :user do
    post "/update_picture_from_facebook" => "users/omniauth_callbacks#update_picture_from_facebook", :as => :update_picture_from_facebook
  end

  get "bar/:bar_id" => "users/bars#show", as: "bar_profile"
  
  resource :users do
    collection do
    end
  end
  
  devise_for :bars, controllers: {registrations: "bars/registrations", sessions: "bars/sessions", confirmations: "bars/confirmations", passwords: "bars/passwords"}

  devise_for :members, controllers: {registrations: "members/registrations"}
  
  namespace :bars do
    get "delete_swig/:id" => "dashboard#delete_swig", as: "delete_swig"
    match  "invite_friend" => "dashboard#after_join_invite_friends", as: "after_join_invite_friends"
    post  "invite_friend_by_email" => "dashboard#invite_friend_by_email", as: "invite_friend_by_email"
    match  "sport_lists" => "dashboard#sport_lists", as: "sport_lists"
    match  "users_lists" => "dashboard#users_lists", as: "users_lists"
    match  "completion" => "dashboard#completion", as: "completion"
    post  "update_completion" => "dashboard#update_completion", as: "update_completion"
    match  "second_completion" => "dashboard#second_completion", as: "second_completion"
    post  "update_second_completion" => "dashboard#update_second_completion", as: "update_second_completion"
    match  "dashboard" => "dashboard#index", as: "dashboard"
    match  "product" => "products#index", as: "product"
    post  "create_reward_message/:user_id/:winner_id" => "dashboard#create_reward_message", as: "create_reward_message"
    post  "create_swig" => "dashboard#create_swig", as: "create_swig"
    post  "create_big_swig" => "dashboard#create_big_swig", as: "create_big_swig"
    post  "update_big_swig" => "dashboard#update_big_swig", as: "update_big_swig"
    get  "delete_big_swig/:ids" => "dashboard#delete_big_swig", as: "delete_big_swig"
    post  "update_swig/:id" => "dashboard#update_swig", as: "update_swig"
    post  "create_loyalty" => "dashboard#create_loyalty", as: "create_loyalty"
    post  "create_popularity" => "dashboard#create_popularity", as: "create_popularity"
    get "edit_loyalty/:id" => "dashboard#edit_loyalty", as: :edit_loyalty
    get "new_loyalty" => "dashboard#new_loyalty", as: :new_loyalty
    get "edit_popularity/:id" => "dashboard#edit_popularity", as: :edit_popularity
    get "new_popularity" => "dashboard#new_popularity", as: :new_popularity
    post  "update_loyalty/:id" => "dashboard#update_loyalty", as: "update_loyalty"
    post  "update_popularity/:id" => "dashboard#update_popularity", as: "update_popularity"
    delete  "delete_loyalty/:id" => "dashboard#delete_loyalty", as: "delete_loyalty"
    delete  "delete_popularity/:id" => "dashboard#delete_popularity", as: "delete_popularity"
    get "rewards/index"
    match "rewards" => "rewards#index", as: "rewards"
    post "create_bar_message" => "dashboard#create_bar_message", as: "create_bar_message"
    post  "create_gift" => "dashboard#create_gift", as: "create_gift"
    post  "activate_loyalty/:loyalty_id" => "dashboard#activate_loyalty", as: "activate_loyalty"
    post  "deactivate_loyalty/:loyalty_id" => "dashboard#deactivate_loyalty", as: "deactivate_loyalty"
    post  "activate_popularity/:popularity_id" => "dashboard#activate_popularity", as: "activate_popularity"
    post  "deactivate_popularity/:popularity_id" => "dashboard#deactivate_popularity", as: "deactivate_popularity"
    post  "update_gift/:gift_id" => "dashboard#update_gift", as: "update_gift"
    get  "destroy_gift_in_list/:gift_id" => "dashboard#destroy_gift_in_list", as: "destroy_gift_in_list"
    post  "add_bigswig_list" => "dashboard#add_bigswig_list", as: "add_bigswig_list"
    post  "add_bigswig_list_on_update" => "dashboard#add_bigswig_list_on_update", as: "add_bigswig_list_on_update"
    post  "add_bar_hours" => "dashboard#add_bar_hours", as: "add_bar_hours"
    post  "add_bar_hours_on_edit" => "dashboard#add_bar_hours_on_edit", as: "add_bar_hours_on_edit"
    post  "add_reward_to_list" => "dashboard#add_reward_to_list", as: "add_reward_to_list"
    get  "destroy_bar_big_swig_list/:bigswiglist_id" => "dashboard#destroy_bar_big_swig_list", as: "destroy_bar_big_swig_list"
    post  "update_bar_big_swig_list/:bigswiglist_id" => "dashboard#update_bar_big_swig_list", as: "update_bar_big_swig_list"
    post  "search_redeem_code/:code" => "dashboard#search_redeem_code", as: "search_redeem_code"
    get  "swiger_list" => "dashboard#swiger_list", as: "swiger_list"
    post  "update_bar_hours" => "dashboard#update_bar_hours", as: "update_bar_hours"
    get  "swigger_total_count" => "dashboard#swigger_total_count", as: "swigger_total_count"
    get "reward_stats" => "dashboard#reward_stats", as: :reward_stats

    resources :messages do
      collection do
        get  "notify_mark_all_read" => "messages#notify_mark_all_read", as: "notify_mark_all_read"
        get  "messages_mark_all_read" => "messages#messages_mark_all_read", as: "messages_mark_all_read"
        get 'notifications'
        get 'sent'
        post 'custom_action(/:form_type)' => "messages#custom_action", as: :custom_action
        get 'trash'
        get 'message_popup'
        get 'new/:user_ids' => "messages#new", as: :new
        post 'reply_message'

      end
    end

  end
  
  resources :bars do
    match "upgrade" => "bars/payment_gateway#index", as: "upgrade"
  end

  namespace :users do
    match  "invite_friend" => "dashboard#after_join_invite_friends_by_email", as: "after_join_invite_friends_by_email"
    match  "invite_friends" => "dashboard#after_join_invite_friends_by_fb", as: "after_join_invite_friends_by_fb"
    post  "invite_friend_by_email" => "dashboard#after_sign_up_invite_friend_by_email", as: "after_sign_up_invite_friend_by_email"
    post  "invite_friend_by_fb" => "dashboard#after_sign_up_invite_friend_by_fb", as: "after_sign_up_invite_friend_by_fb"
    post  "update_user_for_mobile" => "dashboard#update_user_for_mobile", as: "update_user_for_mobile"
    match  "completion" => "dashboard#completion", as: "completion"
    post  "update_completion" => "dashboard#update_completion", as: "update_completion"
    match  "notifications" => "notifications#index", as: "notifications"
    match  "user_dashboard" => "dashboard#index", as: "dashboard"
    match  "facebook_dashboard" => "dashboard#facebook_page", as: "facebook_page"
    match  "facebook_mobile_profile" => "dashboard#facebook_mobile_profile", as: "facebook_mobile_profile"
    match  "facebook_update_status" => "dashboard#facebook_update_status", as: "facebook_update_status"
    match  "invite_swigbig" => "dashboard#invite_swigbig", as: "invite_swigbig"
    post "invite_by_email" => "dashboard#invite_by_email", as: :invite_by_email
    match  "profile/:id" => "dashboard#show", as: "profile"
    match  "rewards" => "dashboard#rewards", as: "rewards"
    match  "update_account" => "dashboard#update_account", as: "update_account"
    match  "update_password" => "dashboard#update_password", as: "update_password"
    get  "show_swig/:bar_id/:swig_id" => "bar_swigs#show_swig", as: "show_swig"
    post  "enter_bar/:bar_id" => "bar_swigs#enter_bar", as: "enter_bar"
    post  "redeem/:bar_id" => "bars#redeem_reward", as: "redeem_reward"
    post "create_popularity/:bar_id" => "bars#create_popularity", as: "create_popularity"
    match "friendship" => "friends#index", as: "friend_index"
    post "friend_request/:id" => "friends#friend_request", as: "friend_request"
    post "remove_friend/:id" => "friends#remove_friend", as: :remove_friend
    post "approve_friend/:id" => "friends#approve_friend", as: :approve_friend
    get  "swiger_list/:bar_id" => "bars#swiger_list", as: "swiger_list"
    get  "mobile_reward" => "dashboard#mobile_reward", as: "mobile_reward"
    get  "lock_post_event" => "dashboard#lock_post_event", as: "lock_post_event"
    get  "unlock_post_event" => "dashboard#unlock_post_event", as: "unlock_post_event"

app/controllers/bars/messages_controller.rb
class Bars::MessagesController < ApplicationController
  layout "bars"

  def index
    @messages = current_bar.received_messages.page(params[:page]).per(10)
  end

  def sent
    @messages_all_user = current_bar.sent_messages.where(category: 5).group(:created_at).page(params[:page]).per(10)
    @messages_last_visit = current_bar.sent_messages.where(category: 1).group(:created_at).page(params[:page]).per(10)
    @messages_almost_rewarded = current_bar.sent_messages.where(category: 2).group(:created_at).page(params[:page]).per(10)
  end

  def new
    @message = ActsAsMessageable::Message.new
  end

  def create
    case params[:category]
    when "0"
      User.all.each do |user|
        BarMessage.create(params[:bar_message].merge(user_id: user.id))
        @message = ActsAsMessageable::Message.new(params[:acts_as_messageable_message])
      end

    when "1"
      User.all.each do |user|
        BarMessage.create(params[:bar_message].merge(user_id: user.id))
      end

    when "2"
      User.all.each do |user|
        BarMessage.create(params[:bar_message].merge(user_id: user.id))
      end

    end

    redirect_to :back, notice: "Message success Send!"

    if @message.save
      redirect_to :back, notice: "Your message has been successfully sent"
    else
      render action: :new
    end

  end

  def create_bar_message; end

  def show
    @message_show = ActsAsMessageable::Message.find(params[:id])
    @message_show.mark_as_read
    @message = ActsAsMessageable::Message.new
  end

  def custom_action
    unless params[:message_ids].blank?
      messages = ActsAsMessageable::Message.where("id IN (?)",params[:message_ids])

      case params[:custom_action]

      when "1"
        messages.each do |message|
          message.mark_as_read
        end
        
      when "2"
        messages.each do |message|
          message.mark_as_unread
        end

      when "3"
        messages.each do |message|
          current_bar.delete_message(message)
        end

      when "4"
        messages.each do |message|
          current_bar.delete_message(message)
        end

      end
    end
    
    redirect_to params[:form_type].blank? ? bars_messages_path : trash_bars_messages_path
  end

  def trash
    @messages = current_bar.deleted_messages.page(params[:page]).per(10)
  end

  def notification
    @notification_unlock_swig = current_bar.sent_messages.where(["category = (?)", 15]).order("created_at DESC").page(params[:page]).per(10)
    @notification_unlock_popularity = current_bar.sent_messages.where(["category = (?)", 9]).order("created_at DESC").page(params[:page]).per(10)
    @notification_unlock_loyalty = current_bar.sent_messages.where(["category = (?)", 16]).order("created_at DESC").page(params[:page]).per(10)
  end

  def message_popup
    @bar_message = ActsAsMessageable::Message.new
  end

  def notify_mark_all_read
    current_bar.messages.update_all('notify_opended = true')

    @total_notification = current_bar.received_messages.where(notify_opended: false).count.to_s
    respond_to :js
  end

  def messages_mark_all_read
    current_bar.messages.update_all('opened = true')

    @total_notification = current_bar.received_messages.where(opened: false).count.to_s
    respond_to :js
  end

  def notifications
    @notifications_popularity_rewards = current_bar.messages.where(category: 9).order('created_at DESC').page(params[:page]).per(5)
    @notifications_loyalty_rewards = current_bar.messages.where(category: 16).order('created_at DESC').page(params[:page]).per(5)
    @notifications_bigswig_rewards = current_bar.messages.where(category: 15).order('created_at DESC').page(params[:page]).per(5)
  end

  def notifications_list_bigswig
    @notifications_bigswig_rewards = current_bar.messages.where(category: 15).order('created_at DESC').page(params[:page]).per(5)

    respond_to :js
  end

  def notifications_list_loyalty
    @notifications_loyalty_rewards = current_bar.messages.where(category: 16).order('created_at DESC').page(params[:page]).per(5)

    respond_to :js
  end

  def notifications_list_popularity
    @notifications_popularity_rewards = current_bar.messages.where(category: 9).order('created_at DESC').page(params[:page]).per(5)

    respond_to :js
  end

  def reply_message
    unless params[:acts_as_messageable_message][:reward].to_i.eql?(22)
      send_to = User.find(params[:acts_as_messageable_message][:to])
    else
      send_to = AdminUser.first
    end

    if send_to
      current_bar.send_message(send_to, {
          topic: params[:acts_as_messageable_message][:topic],
          body: params[:acts_as_messageable_message][:body],
          category: params[:acts_as_messageable_message][:category]
        })
      redirect_to bars_messages_path, notice: 'succses'
    else
      redirect_to :back, notice: 'fails reply!'
    end
  end
  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # The path used after confirmation.
#  def after_confirmation_path_for(resource_name, resource)
#
#  end
end

app/controllers/users/friends_controller.rb
class Users::FriendsController < ApplicationController
  before_filter :authenticate_user!
  
  layout "users"

  def index
    @search = User.search(params[:search])
    @users = @search
    friends = current_user.friendships.pluck(:friend_id).uniq
    @friends_at_bar = Swiger.where(user_id: friends).where(["created_at >= ? AND created_at <= ?", Time.now.to_time.in_time_zone - 1.hours, Time.now.to_time.in_time_zone + 1.hours])
    @current = current_user
    @friends = @current.friends
    @user_pending = current_user.pending_invited
    @user_request = current_user.pending_invited_by

  end

  def show; end

  def invite_friend; end

  def request_list
    @user_request = current_user.pending_invited_by
  end

  def pending_list
    @user_pending_request = current_user.pending_invited
  end

  def friend_request
    @user = User.find(params[:id])
    if current_user.invite @user
      redirect_to :back, notice: "Friend request sent"
    else
      redirect_to :back, notice: "Cannot request friend"
    end
  end


  def approve_friend
    @user = User.find(params[:id])
    if current_user.approve @user
      redirect_to :back, notice: "#{@user.name} added"
    else
      redirect_to :back, notice: "#{@user.name} fail added"
    end
  end

  def remove_friend
    @user = User.find(params[:id])
    current_user.remove_friendship @user
    redirect_to :back , notice: "Removed!"
  end
end

app/controllers/users/notifications_controller.rb
class Users::NotificationsController < ApplicationController
  layout "users"

  def index
    @bar_messages = BarMessage.where(user_id: current_user.id)
    @bar_messages = BarMessage.where(user_id: current_user.id)
    @bar_ids = current_user.swigers.pluck(:bar_id).uniq
    @notifications = ActivityStream.all
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
   layout "users"
end

app/controllers/users/swig_friends_list_controller.rb
class Users::SwigFriendsListController < ApplicationController
  def index; end
end

app/helpers/users/friends_helper.rb
module Users::FriendsHelper

  def check_friend(user1,user2)
    return if user1.eql?(user2)
    if user1.friend_with?(user2)
      "<div class=\"\">  Already friend</div>".html_safe
    elsif user1.connected_with?(user2)
      " <div class=\"\"> Request Pending </div>".html_safe
    else
      " <div class=\"\">  #{button_to "Add as Friend", users_friend_request_path(user2.id.to_i), class: 'btn-success btn-mini'} </div>".html_safe
    end
  end

  #<%= check_friend(current_user, user) %>

end

app/helpers/users/messages_helper.rb
module Users::MessagesHelper
end

app/helpers/users/swig_friends_list_helper.rb
module Users::SwigFriendsListHelper
end

app/views/users/messages/_message_content.html.erb
<% @messages.each do |message| %>
  <% if message.category.eql?(0) or message.category.eql?(1) or message.category.eql?(5) or message.category.eql?(18) %>
    <tr style="cursor: pointer;background-color: <%= message.opened ? "white" : "darkgrey" %>">
      <td class="span2"><%= check_box_tag "message_ids[]", message.id, false, :class => "checkbox" %></td>
      <% if !message.gift_id.blank? %>
        <td class="span5"><%= link_to  message.sent_messageable.name, bar_profile_path(message.sent_messageable) %></td>
        <td class="span2"><div style="width: 25px;"><%= link_to image_tag("/assets/gift.jpeg"), users_message_path(current_user.id)  %></div></td>
      <% elsif !message.reward_id.blank? %>
        <td class="span5"><%= link_to  message.sent_messageable.name, bar_profile_path(message.sent_messageable) %></td>
        <td class="span2"><div style="width: 25px;"><%= link_to  image_tag("/assets/reward.jpg"), users_message_path(current_user.id) %></div></td>
      <% else %>
        <td class="span7"><%= link_to  message.sent_messageable.name, bar_profile_path(message.sent_messageable) %></td>
      <% end %>
      <td class="span10" onclick="window.location.href='<%= users_message_url(message) %>'"><b><%= message.topic %></b> - <%= truncate(strip_tags(message.body.html_safe), length: 40) %></td>
      <td class="span4" onclick="window.location.href='<%= users_message_url(message) %>'"><%= format_date_global(message.created_at) %></td>
    </tr>
  <% elsif message.category.eql?(30) %>
    <tr style="cursor: pointer;background-color: <%= message.opened ? "white" : "darkgrey" %>">
      <td class="span2"><%= check_box_tag "message_ids[]", message.id, false, :class => "checkbox" %></td>
      <td class="span5"><%= link_to  message.sent_messageable.name, bar_profile_path(message.sent_messageable) %></td>
      <td class="span2"><div style="width: 25px;"><%= link_to image_tag("/assets/gift.jpeg"), users_message_path(current_user.id)  %></div></td>
      <td class="span10" onclick="window.location.href='<%= users_message_url(message) %>'"><b><%= message.topic %></b> - <%= truncate(strip_tags(message.body.html_safe), length: 40) %></td>
      <td class="span4" onclick="window.location.href='<%= users_message_url(message) %>'"><%= format_date_global(message.created_at) %></td>
    </tr>
  <% elsif message.category.eql?(31) %>
    <tr style="cursor: pointer;background-color: <%= message.opened ? "white" : "darkgrey" %>">
      <td class="span2"><%= check_box_tag "message_ids[]", message.id, false, :class => "checkbox" %></td>
      <td class="span5"><%= link_to  message.sent_messageable.name, bar_profile_path(message.sent_messageable) %></td>
      <td class="span2"><div style="width: 25px;"><%= link_to  image_tag("/assets/reward.jpg"), users_message_path(current_user.id) %></div></td>
      <td class="span10" onclick="window.location.href='<%= users_message_url(message) %>'"><b><%= message.topic %></b> - <%= truncate(strip_tags(message.body.html_safe), length: 40) %></td>
      <td class="span4" onclick="window.location.href='<%= users_message_url(message) %>'"><%= format_date_global(message.created_at) %></td>
    </tr>
  <% elsif message.category.eql?(6) or message.category.eql?(7) or message.category.eql?(8)  %>
    <tr style="cursor: pointer;background-color: <%= message.opened ? "white" : "darkgrey" %>">
      <td class="span2"><%= check_box_tag "message_ids[]", message.id, false, :class => "checkbox" %></td>
      <td class="span7"><%= link_to  message.sent_messageable.name, bar_profile_path(message.sent_messageable) %></td>
      <td class="span10" onclick="window.location.href='<%= users_message_url(message) %>'"><b><%= message.topic %></b> - <%= truncate(strip_tags(message.body.html_safe), length: 40) %></td>
      <td class="span4" onclick="window.location.href='<%= users_message_url(message) %>'"><%= format_date_global(message.created_at) %></td>
    </tr>
  <% elsif message.category.eql?(9) %>
    <tr style="cursor: pointer;background-color: <%= message.opened ? "white" : "darkgrey" %>">
      <td class="span2"><%= check_box_tag "message_ids[]", message.id, false, :class => "checkbox" %></td>
      <td class="span7"><%= link_to  message.sent_messageable.name, bar_profile_path(message.sent_messageable) %></td>
      <td class="span10" onclick="window.location.href='<%= users_message_url(message) %>'"><b><%= message.topic %></b> - <%= truncate(strip_tags(message.body.html_safe), length: 40) %></td>
      <td class="span4" onclick="window.location.href='<%= users_message_url(message) %>'"><%= format_date_global(message.created_at) %></td>
    </tr>
  <% elsif message.category.eql?(11) %>
    <tr style="cursor: pointer;background-color: <%= message.opened ? "white" : "darkgrey" %>">
      <td class="span2"><%= check_box_tag "message_ids[]", message.id, false, :class => "checkbox" %></td>
      <td class="span7"><%= link_to  message.sent_messageable.name, users_message_path(current_user.id) %></td>
      <td class="span10" onclick="window.location.href='<%= users_message_url(message) %>'"><b><%= message.topic %></b> - <%= truncate(strip_tags(message.body.html_safe), length: 40) %></td>
      <td class="span4" onclick="window.location.href='<%= users_message_url(message) %>'"><%= format_date_global(message.created_at) %></td>
    </tr>
  <% elsif message.category.eql?(15) %>
    <tr style="cursor: pointer;background-color: <%= message.opened ? "white" : "darkgrey" %>">
      <td class="span2"><%= check_box_tag "message_ids[]", message.id, false, :class => "checkbox" %></td>
      <td class="span5"><%= link_to  message.sent_messageable.name, bar_profile_path(message.sent_messageable) %></td>
      <td class="span2"><div style="width: 25px;"><%= link_to  image_tag("/assets/Unlock-icon.png"), users_message_path(current_user.id) %></div></td>
      <td class="span10" onclick="window.location.href='<%= users_message_url(message) %>'"><b><%= message.topic %></b> - <%= truncate(strip_tags(message.body.html_safe), length: 40) %></td>
      <td class="span4" onclick="window.location.href='<%= users_message_url(message) %>'"><%= format_date_global(message.created_at) %></td>
    </tr>
  <% elsif message.category.eql?(16) %>
    <tr style="cursor: pointer;background-color: <%= message.opened ? "white" : "darkgrey" %>">
      <td class="span2"><%= check_box_tag "message_ids[]", message.id, false, :class => "checkbox" %></td>
      <td class="span5"><%= link_to  message.sent_messageable.name, bar_profile_path(message.sent_messageable) %></td>
      <td class="span2"><div style="width: 25px;"><%= link_to  image_tag("/assets/gift.jpg"), users_message_path(current_user.id) %></div></td>
      <td class="span10" onclick="window.location.href='<%= users_message_url(message) %>'"><b><%= message.topic %></b> - <%= truncate(strip_tags(message.body.html_safe), length: 40) %></td>
      <td class="span4" onclick="window.location.href='<%= users_message_url(message) %>'"><%= format_date_global(message.created_at) %></td>
    </tr>
  <% elsif message.category.eql?(22) %>
    <tr style="cursor: pointer;background-color: <%= message.opened ? "white" : "darkgrey" %>">
      <td class="span2"><%= check_box_tag "message_ids[]", message.id, false, :class => "checkbox" %></td>
      <td class="span7"><b style="color: greenyellow;">"SwigBIG Admin"</b></td>
      <td class="span10" onclick="window.location.href='<%= users_message_url(message) %>'"><b><%= message.topic %></b> - <%= truncate(strip_tags(message.body.html_safe), length: 40) %></td>
      <td class="span4" onclick="window.location.href='<%= users_message_url(message) %>'"><%= format_date_global(message.created_at) %></td>
    </tr>
  <% elsif message.category.eql?(24) %>
    <tr style="cursor: pointer;background-color: <%= message.opened ? "white" : "darkgrey" %>">
      <td class="span2"><%= check_box_tag "message_ids[]", message.id, false, :class => "checkbox" %></td>
      <td class="span6"><%= link_to  message.sent_messageable.name, bar_profile_path(message.sent_messageable) %></td>
      <td class="span11" onclick="window.location.href='<%= users_message_url(message) %>'"><b><%= message.topic %></b> - <%= truncate(strip_tags(message.body.html_safe), length: 40) %></td>
      <td class="span4" onclick="window.location.href='<%= users_message_url(message) %>'"><%= format_date_global(message.created_at) %></td>
    </tr>
  <% end %>
<% end %>

app/views/users/messages/_message_menu.html.erb
<!--<div style="float:left;width: 20%;border-right: 1px solid black;padding:10px;min-height: 400px;">-->
<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Messages Menu</li>
      <li class="span1">
        <!--<a class=""  href="#bar_message" data-toggle="modal" >New</a>-->
      </li>
      <li class="span1">
        <%= link_to "Inbox", users_messages_path %>
      </li>
      <li class="span1">
        <%= link_to "Sent", sent_users_messages_path %>
      </li>
      <li class="span1">
        <%= link_to "Trash", trash_users_messages_path %>
      </li>
    </ul>
    <div style="clear: both"></div>
  </div>
  <div class="clear"></div>
</div>

app/views/users/messages/_side_menu.erb
<script type="text/css">
  #sidebar {
  float:left;
  width:175px;
  background:#c9c;
  }
  #left_side {
  float:left;
  margin-right:35%;
  width:63%;
  }
  #right_side{
  float:right;
  margin-left:-65%;
  width:35%;
  }
</script>

<%= link_to "Index", users_messages_path %> |
<%= link_to "Inbox", users_message_inbox_path %> |
<%= link_to "Outbox", users_message_outbox_path %>|
<%= link_to "New", new_users_message_path %>

app/views/users/messages/index.js.erb
$('#message_list').html('<%= escape_javascript(render("message_content")) %>');
$('#message_paginator').html('<%= escape_javascript(paginate(@messages, :remote => true).to_s) %>');

app/views/users/messages/messages_mark_all_read.js.erb
$('#messages_red').html("<%=j @total_notification %>")

app/views/users/messages/notifications.js.erb
$('#notification_list').html('<%= escape_javascript(render("notifications_content")) %>');
$('#notification_paginator').html('<%= escape_javascript(paginate(@notifications, :remote => true).to_s) %>');